Repository nmstate/kubernetes-nmstate, pull requests merged in 2019-12, with the labels that each got.

#298 Prow fixes
  Makefile
  stdci.yaml
Labels: dco-signoff: yes, size/S

#285 Matching state
  pkg/apis/nmstate/v1alpha1/nodenetworkconfigurationenactment_types.go
  pkg/controller/nodenetworkconfigurationpolicy/conditions/enactments.go
  pkg/controller/nodenetworkconfigurationpolicy/conditions/manager.go
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_controller.go
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_controller_test.go
  pkg/controller/nodenetworkconfigurationpolicy/selectors/labels.go
  pkg/controller/nodenetworkconfigurationpolicy/selectors/labels_test.go
  pkg/controller/nodenetworkconfigurationpolicy/selectors/selectors.go
  pkg/controller/nodenetworkconfigurationpolicy/selectors/selectors_suite_test.go
  test/e2e/nnce_conditions_test.go
  test/e2e/node_selector_test.go
  test/e2e/utils.go
Labels: dco-signoff: yes, size/XL

#301 add OWNERS to enable Prow functionality
  OWNERS
Labels: dco-signoff: yes, size/XS

#304 add issue and PR templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dco-signoff: yes, size/M

#300 Policy overall conditions
  go.mod
  pkg/apis/nmstate/v1alpha1/nodenetworkconfigurationenactment_types.go
  pkg/apis/nmstate/v1alpha1/nodenetworkconfigurationpolicy_types.go
  pkg/controller/nodenetworkconfigurationpolicy/conditions/enactments.go
  pkg/controller/nodenetworkconfigurationpolicy/conditions/manager.go
  pkg/controller/nodenetworkconfigurationpolicy/enactmentconditions/conditions.go
  pkg/controller/nodenetworkconfigurationpolicy/enactmentconditions/counter.go
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_controller.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions_test.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/policyconditions_suite_test.go
  test/e2e/conditions.go
  test/e2e/nncp_cleanup_test.go
  test/e2e/rollback_test.go
  test/e2e/utils.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XL

#307 Force Get enacment after update
  pkg/controller/nodenetworkconfigurationpolicy/enactmentconditions/conditions.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/S

#308 docs: use dhcp for cluster-wide policies
  docs/user-guide-policy-configure-linux-bond-with-vlans.md
  docs/user-guide-policy-configure-linux-bond.md
  docs/user-guide-policy-configure-linux-bridge.md
  docs/user-guide-policy-configure-ovs-bridge.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#318 Disable okd lane
  automation/check-patch.e2e-okd.sh
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#317 Fix e2e test races
  automation/check-patch.e2e-k8s.sh
  pkg/apis/nmstate/v1alpha1/nodenetworkconfigurationenactment_types.go
  pkg/controller/nodenetworkconfigurationpolicy/enactmentconditions/conditions.go
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_controller.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions.go
  pkg/helper/client.go
  test/e2e/node_selector_test.go
  test/e2e/rollback_test.go
  test/e2e/utils.go
Labels: dco-signoff: yes, release-note-none, size/L
