Repository nmstate/kubernetes-nmstate, pull requests merged in 2020-02, with the labels that each got.

#369 Changing the way format and check works
  Makefile
  test/e2e/bonding_default_interface_test.go
  test/e2e/simple_vlan_and_ip_test.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#361 Run webhook only on master nodes
  cmd/manager/main.go
  deploy/operator.yaml
  hack/cluster-sync-handler.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#345 Add Makefile targets to prepare a release
  CONTRIBUTING.md
  Makefile
  hack/bump-version.sh
  hack/prepare-release.sh
  hack/version.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#372 Add Alona, Eran and Igal to reviewers
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#373 Gather e2e tests logs in parallel and improve some logs
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-ocp.sh
  automation/check-patch.e2e-okd.sh
  test/e2e/main_test.go
  test/e2e/nnce_conditions_test.go
  test/e2e/reporter.go
  test/e2e/reporter/reporter.go
  test/e2e/reporter/writers.go
  test/e2e/rollback_test.go
  test/e2e/runner/node.go
  test/e2e/runner/pod.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#368 docs: 101 state
  README.md
  docs/user-guide-101-reporting-state.md
  docs/user-guide-state-reporting.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#379 Release v0.14.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#382 Add a link to the vlan and ip configuration user guide
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#383 Move e2e libs to separate path
  Makefile
  test/e2e/main_test.go
  test/e2e/nnce_conditions_test.go
  test/e2e/rollback_test.go
  test/e2e/utils.go
  test/reporter/reporter.go
  test/reporter/writers.go
  test/runner/node.go
  test/runner/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#380 Default to 0 if numberAvailable is not present
  hack/cluster-sync-handler.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#385 test/e2e: Set secondary nics down at teardown
  test/e2e/bonding_default_interface_test.go
  test/e2e/states.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#381 Integrate kube-admission-webhook module
  go.mod
  go.sum
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
  vendor/github.com/onsi/gomega/gstruct/elements.go
  vendor/github.com/onsi/gomega/gstruct/errors/nested_types.go
  vendor/github.com/onsi/gomega/gstruct/fields.go
  vendor/github.com/onsi/gomega/gstruct/ignore.go
  vendor/github.com/onsi/gomega/gstruct/keys.go
  vendor/github.com/onsi/gomega/gstruct/pointer.go
  vendor/github.com/onsi/gomega/gstruct/types.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/github.com/qinqon/kube-admission-webhook/LICENSE
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/ca.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/csr.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/store.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#378 Fix ocp lane
  Makefile
  automation/check-patch.e2e-ocp.sh
  automation/check-patch.e2e-okd.sh
  cmd/manager/main.go
  hack/flush-secondary-nics.sh
  hack/install-kubevirtci.sh
  test/e2e/bonding_default_interface_test.go
  test/e2e/default_bridged_network_test.go
  test/e2e/main_test.go
  test/e2e/multiple_policies_for_same_node_test.go
  test/e2e/nodes_test.go
  test/e2e/rollback_test.go
  test/e2e/simple_bridge_and_bond_test.go
  test/e2e/simple_vlan_and_ip_test.go
  test/e2e/states.go
  test/e2e/utils.go
  test/runner/node.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#386 Adding profiler:
  CONTRIBUTING.md
  cmd/manager/main.go
  deploy/operator.yaml
  vendor/github.com/kelseyhightower/envconfig/.travis.yml
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/MAINTAINERS
  vendor/github.com/kelseyhightower/envconfig/README.md
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/go.mod
  vendor/github.com/kelseyhightower/envconfig/usage.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XL

#391 test: move kubectl to a separate module
  test/cmd/kubectl.go
  test/cmd/run.go
  test/runner/node.go
  test/runner/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#393 wait for scc resource
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#387 use NM 1.22 on Kubernetes kubevirtci
  hack/install-nm.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#388 don't retry the configuration
  pkg/helper/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#400 doc: add ubuntu netplan configuration
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#397 test/e2e: Check master/worker daemonsets
  test/e2e/prepare.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#392 docs: 102 Configuration
  README.md
  docs/examples/bond0-eth1-eth2_absent.yaml
  docs/examples/bond0-eth1-eth2_up.yaml
  docs/examples/eth1-eth2_up.yaml
  docs/examples/vlan100_node01_up.yaml
  docs/user-guide-101-reporting.md
  docs/user-guide-102-configuration.md
  test/e2e/demos_test.go
  test/e2e/states.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#404 tests: fix cleanup function
  test/e2e/demos_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#395 docs: troubleshooting
  README.md
  docs/examples/eth666_up.yaml
  docs/user-guide-102-configuration.md
  docs/user-guide-103-troubleshooting.md
  test/e2e/demos_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#406 cleanup vlan100 Policy
  test/e2e/demos_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#403 add supported networkmanager version to README
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#405 Move nmstatectl logic to separate package
  pkg/helper/client.go
  pkg/nmstatectl/nmstatectl.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#410 Revert "use NM 1.22 on Kubernetes kubevirtci"
  hack/install-nm.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#407 Use policy generation to calculate overall condition.
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
  pkg/apis/nmstate/v1alpha1/nodenetworkconfigurationenactment_types.go
  pkg/apis/nmstate/v1alpha1/zz_generated.openapi.go
  pkg/controller/nodenetworkconfigurationpolicy/enactmentstatus/conditions/conditions_suite_test.go
  pkg/controller/nodenetworkconfigurationpolicy/enactmentstatus/conditions/counter.go
  pkg/controller/nodenetworkconfigurationpolicy/enactmentstatus/conditions/counter_test.go
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_controller.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#412 pin nmstate to 0.2 branch
  build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#411 Release v0.15.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#414 add missing variables configuring profiling
  deploy/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#419 remove user_setup
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#418 bump NetworkManager requirements to 1.22
  CONTRIBUTING.md
  README.md
  build/Dockerfile
  hack/install-nm.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#420 Change webhook port to 54874
  deploy/operator.yaml
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#423 [release-0.15] explicitly bring unavailable interfaces up
  pkg/nmstatectl/nmstatectl.go
  pkg/nmstatectl/unavailable_link_workaround.go
  vendor/github.com/godbus/dbus/.travis.yml
  vendor/github.com/godbus/dbus/CONTRIBUTING.md
  vendor/github.com/godbus/dbus/LICENSE
  vendor/github.com/godbus/dbus/MAINTAINERS
  vendor/github.com/godbus/dbus/README.markdown
  vendor/github.com/godbus/dbus/auth.go
  vendor/github.com/godbus/dbus/auth_external.go
  vendor/github.com/godbus/dbus/auth_sha1.go
  vendor/github.com/godbus/dbus/call.go
  vendor/github.com/godbus/dbus/conn.go
  vendor/github.com/godbus/dbus/conn_darwin.go
  vendor/github.com/godbus/dbus/conn_other.go
  vendor/github.com/godbus/dbus/dbus.go
  vendor/github.com/godbus/dbus/decoder.go
  vendor/github.com/godbus/dbus/default_handler.go
  vendor/github.com/godbus/dbus/doc.go
  vendor/github.com/godbus/dbus/encoder.go
  vendor/github.com/godbus/dbus/export.go
  vendor/github.com/godbus/dbus/homedir.go
  vendor/github.com/godbus/dbus/homedir_dynamic.go
  vendor/github.com/godbus/dbus/homedir_static.go
  vendor/github.com/godbus/dbus/message.go
  vendor/github.com/godbus/dbus/object.go
  vendor/github.com/godbus/dbus/server_interfaces.go
  vendor/github.com/godbus/dbus/sig.go
  vendor/github.com/godbus/dbus/transport_darwin.go
  vendor/github.com/godbus/dbus/transport_generic.go
  vendor/github.com/godbus/dbus/transport_tcp.go
  vendor/github.com/godbus/dbus/transport_unix.go
  vendor/github.com/godbus/dbus/transport_unixcred_dragonfly.go
  vendor/github.com/godbus/dbus/transport_unixcred_freebsd.go
  vendor/github.com/godbus/dbus/transport_unixcred_linux.go
  vendor/github.com/godbus/dbus/transport_unixcred_openbsd.go
  vendor/github.com/godbus/dbus/variant.go
  vendor/github.com/godbus/dbus/variant_lexer.go
  vendor/github.com/godbus/dbus/variant_parser.go
  vendor/github.com/phoracek/networkmanager-go/LICENSE
  vendor/github.com/phoracek/networkmanager-go/src/checkpoint.go
  vendor/github.com/phoracek/networkmanager-go/src/client.go
  vendor/github.com/phoracek/networkmanager-go/src/connection.go
  vendor/github.com/phoracek/networkmanager-go/src/device.go
  vendor/github.com/phoracek/networkmanager-go/src/settings.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#426 Release v0.15.1
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#431 Disable webhooks
  deploy/operator.yaml
  test/e2e/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#433 Release v0.15.2
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#434 Set nmstatectl 'set' timeout to (defaultGwProbe + apiServerProbe) * 2
  pkg/helper/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#436 Release v0.15.3
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#439 remove the webhook manifest
  deploy/operator.yaml
Labels: dco-signoff: yes, release-note-none, size/L
