Repository nmstate/kubernetes-nmstate, pull requests merged in 2020-05, with the labels that each got.

#522 add installation guide to release notes
  Makefile
  hack/prepare-release.sh
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/S

#521 we are NMState
  deploy/crds/nmstate.io_nmstates_crd.yaml
  deploy/crds/nmstate.io_v1alpha1_nmstate_cr.yaml
  pkg/apis/nmstate/v1alpha1/nmstate_types.go
  pkg/apis/nmstate/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/nmstate/nmstate_controller.go
  pkg/controller/nmstate/nmstate_controller_test.go
  pkg/controller/nmstate/nmstate_suite_test.go
  pkg/names/names.go
  test/e2e/operator/main_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#520 Use correct crd name in clean script
  cluster/clean.sh
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#524 Add missing test policy waits
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/examples_test.go
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/nnce_desiredstate_test.go
  test/e2e/handler/nncp_cleanup_test.go
  test/e2e/handler/rollback_test.go
  test/e2e/handler/simple_bridge_and_bond_test.go
  test/e2e/handler/simple_ovs_bridge_test.go
  test/e2e/handler/simple_vlan_and_ip_test.go
  test/e2e/handler/user_guide_test.go
  test/e2e/handler/utils.go
  test/e2e/handler/webhook_test.go
Labels: approved, dco-signoff: yes, kind/bug, kind/test, lgtm, release-note-none, size/L

#514 Add optional node selector field to NMstate CRD
  deploy/crds/nmstate.io_nmstates_crd.yaml
  deploy/handler/operator.yaml
  pkg/apis/nmstate/v1alpha1/nmstate_types.go
  pkg/apis/nmstate/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/nmstate/nmstate_controller.go
  pkg/controller/nmstate/nmstate_controller_test.go
  pkg/controller/nmstate/nmstate_suite_test.go
  pkg/controller/nmstate/testdata/kubernetes-nmstate/crds/.gitkeep
  pkg/controller/nmstate/testdata/kubernetes-nmstate/handler/.gitkeep
  pkg/controller/nmstate/testdata/kubernetes-nmstate/namespace/.gitkeep
  pkg/controller/nmstate/testdata/kubernetes-nmstate/rbac/.gitkeep
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#523 Promote operator version to v1beta1
  Makefile
  cluster/clean.sh
  cluster/sync.sh
  deploy/crds/nmstate.io_nmstates_crd.yaml
  deploy/crds/nmstate.io_v1beta1_nmstate_cr.yaml
  hack/prepare-release.sh
  pkg/apis/addtoscheme_nmstate_v1beta1.go
  pkg/apis/nmstate/group.go
  pkg/apis/nmstate/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/nmstate/v1beta1/doc.go
  pkg/apis/nmstate/v1beta1/nmstate_types.go
  pkg/apis/nmstate/v1beta1/register.go
  pkg/apis/nmstate/v1beta1/zz_generated.deepcopy.go
  pkg/apis/nmstate/v1beta1/zz_generated.openapi.go
  pkg/controller/nmstate/nmstate_controller.go
  pkg/controller/nmstate/nmstate_controller_test.go
  test/e2e/operator/main_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#528 Wait for fresh nns after reboot at test
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/default_bridged_network_test.go
  test/e2e/handler/utils.go
Labels: approved, dco-signoff: yes, kind/bug, kind/test, lgtm, release-note-none, size/S

#497 Move webhook to a Deployment
  cluster/clean.sh
  cluster/sync.sh
  cmd/manager/main.go
  deploy/handler/operator.yaml
  deploy/handler/role.yaml
  deploy/operator/role.yaml
  go.mod
  go.sum
  pkg/controller/add_node.go
  pkg/controller/add_nodenetworkconfigurationpolicy.go
  pkg/controller/nmstate/nmstate_controller_test.go
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_controller.go
  pkg/environment/environment.go
  pkg/environment/operator.go
  pkg/helper/client.go
  pkg/helper/node.go
  pkg/probe/probes.go
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
  test/e2e/handler/prepare.go
  test/e2e/handler/rollback_test.go
  test/runner/pod.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/ca.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/client.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/configuration.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/csr.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/store.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/triple/cert.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/triple/pem.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/triple/triple.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/k8s.io/client-go/util/certificate/OWNERS
  vendor/k8s.io/client-go/util/certificate/certificate_manager.go
  vendor/k8s.io/client-go/util/certificate/certificate_store.go
  vendor/k8s.io/client-go/util/certificate/csr/csr.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XXL

#530 Release v0.20.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#427 Add dockerignore to project
  .dockerignore
Labels: approved, dco-signoff: yes, kind/infrastructure, lgtm, release-note-none, size/M

#535 Brad as maintainer
  OWNERS
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/XS

#533 Makefile: remove build dependency on generated files
  Makefile
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-ocp.sh
  automation/check-patch.e2e-okd.sh
  automation/check-patch.e2e-operator-k8s.sh
  automation/check-patch.e2e-operator-ocp.sh
  automation/check-patch.e2e-operator-okd.sh
  hack/check-gen.sh
  vendor/github.com/gobuffalo/envy/.env
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/M

#537 Replace 'aktau/github-release' with 'github-release/github-release'
  go.mod
  go.sum
  hack/vendor-tools.sh
  tools.go
  vendor/github.com/aktau/github-release/LICENSE
  vendor/github.com/github-release/github-release/.gitignore
  vendor/github.com/github-release/github-release/CONTRIBUTING.md
  vendor/github.com/github-release/github-release/Gopkg.lock
  vendor/github.com/github-release/github-release/Gopkg.toml
  vendor/github.com/github-release/github-release/Makefile
  vendor/github.com/github-release/github-release/README.md
  vendor/github.com/github-release/github-release/assets.go
  vendor/github.com/github-release/github-release/cmd.go
  vendor/github.com/github-release/github-release/commit.go
  vendor/github.com/github-release/github-release/error.go
  vendor/github.com/github-release/github-release/github-release.go
  vendor/github.com/github-release/github-release/release
  vendor/github.com/github-release/github-release/releases.go
  vendor/github.com/github-release/github-release/tags.go
  vendor/github.com/github-release/github-release/term.go
  vendor/github.com/github-release/github-release/util.go
  vendor/github.com/github-release/github-release/version.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, kind/infrastructure, lgtm, release-note-none, size/M

#540 oath of a contributor
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#544 Disable tier1 tests ssh strict host check
  test/e2e/openshift.cnv.workflow.sh
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#546 Dump always ssh.sh
  test/e2e/openshift.cnv.workflow.sh
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#547 Increase time waiting for enactment deletion
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#548 Dump junit.functest.xml at tier1 tests
  test/e2e/openshift.cnv.workflow.sh
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/XS

#552 Fix RBAC for secrets watching
  deploy/handler/role.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#529 fix prepare-release.sh EOF
  hack/prepare-release.sh
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#559 Disable tier1 tests ssh strict host check (#544)
  test/e2e/openshift.cnv.workflow.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#560 Dump always ssh.sh (#546)
  test/e2e/openshift.cnv.workflow.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#553 Allow external arguments to tier1 tests script.
  test/e2e/openshift.cnv.workflow.sh
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/XS

#554 Add polarion test_id's
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/node_selector_test.go
  test/e2e/handler/nodes_test.go
  test/e2e/handler/rollback_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#555 Use kubevirt junit and polarion ginkgo reporters
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
  go.mod
  go.sum
  test/e2e/handler/main_test.go
  test/e2e/operator/main_test.go
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/XL

#556 Increase time waiting for enactment deletion
  test/e2e/handler/utils.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#558 Increase logging at e2e nnce conditions tests
  test/e2e/handler/nnce_conditions_test.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/M

#563 Release v0.21.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
