Repository nmstate/kubernetes-nmstate, pull requests merged in 2020-01, with the labels that each got.

#319 Re-read policy on conflict
  automation/check-patch.e2e-k8s.sh
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_controller.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions.go
  test/e2e/nnce_conditions_test.go
  test/e2e/nncp_cleanup_test.go
  test/e2e/simple_bridge_and_bond.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#321 Retrieve policy at unit/test
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions_test.go
Labels: approved, dco-signoff: yes, do-not-merge/hold, do-not-merge/release-note-label-needed, lgtm, size/XS

#320 Add e2e test waitFor functions for common policy conditions
  deploy/role.yaml
  pkg/helper/client.go
  test/e2e/conditions.go
  test/e2e/default_bridged_network_test.go
  test/e2e/nnce_conditions_test.go
  test/e2e/nncp_cleanup_test.go
  test/e2e/node_selector_test.go
  test/e2e/rollback_test.go
  test/e2e/simple_bridge_and_bond.go
  test/e2e/simple_ovs_bridge.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#322 Add check-patch.unit-test.sh
  .travis.yml
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-okd.sh
  automation/check-patch.e2e.setup.sh
  automation/check-patch.setup.sh
  automation/check-patch.unit-test.sh
  hack/whitespace.sh
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions.go
Labels: approved, dco-signoff: yes, release-note-none, size/M

#287 Enactment desiredstate
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies_crd.yaml
  pkg/apis/nmstate/v1alpha1/nodenetworkconfigurationenactment_types.go
  pkg/apis/nmstate/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/nmstate/v1alpha1/zz_generated.openapi.go
  pkg/controller/nodenetworkconfigurationpolicy/enactmentstatus/conditions/conditions.go
  pkg/controller/nodenetworkconfigurationpolicy/enactmentstatus/conditions/counter.go
  pkg/controller/nodenetworkconfigurationpolicy/enactmentstatus/status.go
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_controller.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions_test.go
  test/e2e/nnce_desiredstate_test.go
Labels: approved, dco-signoff: yes, size/L

#326 Add script to publish to quay.io
  automation/publish.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#328 Retry default gw retrieval on error
  pkg/helper/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#332 Clean FDescribe
  test/e2e/rollback_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#330 Add script to automatize github release
  automation/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#333 release v0.13.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#334 Fix release scripts
  hack/release.sh
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#336 Use repo and tag for git push at release
  hack/release.sh
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/XS

#337 add OCP 4.3 CI lane
  automation/check-patch.e2e-k8s.mounts
  automation/check-patch.e2e-k8s.packages
  automation/check-patch.e2e-ocp.sh
  automation/check-patch.e2e-okd.mounts
  automation/check-patch.e2e-okd.packages
  automation/check-patch.e2e.mounts
  automation/check-patch.e2e.packages
  hack/install-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#338 get latest fix with jq installed on OpenShift providers
  hack/install-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#340 Replace e2e test for nns cleanup with unit test
  Makefile
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-ocp.sh
  automation/check-patch.e2e-okd.sh
  pkg/controller/node/node_controller_test.go
  pkg/controller/node/node_suite_test.go
  test/e2e/nns_cleanup_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#344 Call generators before handler build
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#306 Use matching state at policy condition
  pkg/controller/nodenetworkconfigurationpolicy/enactmentstatus/conditions/counter.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#310 Add junit and polarion reporters
  .gitignore
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-ocp.sh
  automation/check-patch.e2e-okd.sh
  automation/check-patch.setup.sh
  automation/check-patch.unit-test.sh
  pkg/apis/nmstate/v1alpha1/v1alpha1_suite_test.go
  pkg/controller/node/node_suite_test.go
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_suite_test.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/policyconditions_suite_test.go
  pkg/controller/nodenetworkconfigurationpolicy/selectors/selectors_suite_test.go
  pkg/helper/helper_suite_test.go
  test/e2e/main_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#347 Always copy junit reports at CI
  Makefile
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-ocp.sh
  automation/check-patch.e2e-okd.sh
  automation/check-patch.unit-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#351 Rename tests
  test/e2e/simple_bridge_and_bond_test.go
  test/e2e/simple_ovs_bridge_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#353 Renamed docs/developer-guide.md to docs/CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  docs/deployment-local-cluster.md
  docs/developer-guide-commands.md
  docs/developer-guide.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/L

#352 Pin and install go from go.mod version
  Makefile
  automation/check-patch.setup.sh
  go.mod
  hack/install-go.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#350 add test for bonding as the default interface
  test/e2e/bonding_default_interface_test.go
  test/e2e/default_bridged_network_test.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#348 Added multiple_policies_for_same_node.go e2e test
  test/e2e/multiple_policies_for_same_node_test.go
  test/e2e/states.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#339 Use k8s 1.17.0 provider
  Makefile
  automation/check-patch.e2e-k8s.sh
  cmd/manager/main.go
  hack/flush-secondary-nics.sh
  hack/install-kubevirtci.sh
  pkg/helper/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#356 Rename e2e junit report to make flakefinder happy
  test/e2e/main_test.go
Labels: approved, dco-signoff: yes, release-note-none, size/XS

#358 drop outdated guides and merge developer guide
  CONTRIBUTING.md
  docs/deployment-local-cluster.md
  docs/developer-guide-commands.md
  docs/developer-guide-node.md
  docs/developer-guide-policy.md
  docs/developer-guide-state.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#363 drop user guides root
  README.md
  docs/deployment-arbitrary-cluster.md
  docs/deployment-local-cluster.md
  docs/user-guide.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#365 Mark ovs test as pending
  test/e2e/simple_ovs_bridge_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#364 Add the flakefinder link to the knmstate welcome page
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#360 e2e tests baseline validation
  test/e2e/main_test.go
  test/e2e/nnce_conditions_test.go
  test/e2e/nnce_desiredstate_test.go
  test/e2e/nodes_test.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M

#366 Count seconds instead of nano for default gw retrieval
  pkg/helper/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#367 make readme straight to the point
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#362 Improve log gathering:
  .gitignore
  Makefile
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-ocp.sh
  automation/check-patch.e2e-okd.sh
  automation/check-patch.setup.sh
  test/e2e/main_test.go
  test/e2e/reporter.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#370 We don't care about the list of file inside golang tarball
  hack/install-go.sh
  pkg/helper/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#374 expose Reason on NNCP and NNCE list
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies_crd.yaml
  pkg/apis/nmstate/v1alpha1/nodenetworkconfigurationenactment_types.go
  pkg/apis/nmstate/v1alpha1/nodenetworkconfigurationpolicy_types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#376 Katacoda
  README.md
  docs/example_bond0-eth1-eth2.yaml
  docs/user-guide-101-reporting-state.md
  docs/user-guide-102-configuring-policy-and-enactment.md
  docs/user-guide-state-reporting.md
  kubernetes-nmstate-introduction/finish.md
  kubernetes-nmstate-introduction/index.json
  kubernetes-nmstate-introduction/intro.md
  kubernetes-nmstate-introduction/step1.md
  kubernetes-nmstate-introduction/step10.md
  kubernetes-nmstate-introduction/step2.md
  kubernetes-nmstate-introduction/step3.md
  kubernetes-nmstate-introduction/step4.md
  kubernetes-nmstate-introduction/step5.md
  kubernetes-nmstate-introduction/step6.md
  kubernetes-nmstate-introduction/step7.md
  kubernetes-nmstate-introduction/step8.md
  kubernetes-nmstate-introduction/step9.md
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#377 Revert "Katacoda"
  README.md
  docs/example_bond0-eth1-eth2.yaml
  docs/user-guide-101-reporting-state.md
  docs/user-guide-102-configuring-policy-and-enactment.md
  docs/user-guide-state-reporting.md
  kubernetes-nmstate-introduction/finish.md
  kubernetes-nmstate-introduction/index.json
  kubernetes-nmstate-introduction/intro.md
  kubernetes-nmstate-introduction/step1.md
  kubernetes-nmstate-introduction/step10.md
  kubernetes-nmstate-introduction/step2.md
  kubernetes-nmstate-introduction/step3.md
  kubernetes-nmstate-introduction/step4.md
  kubernetes-nmstate-introduction/step5.md
  kubernetes-nmstate-introduction/step6.md
  kubernetes-nmstate-introduction/step7.md
  kubernetes-nmstate-introduction/step8.md
  kubernetes-nmstate-introduction/step9.md
Labels: dco-signoff: no, do-not-merge/release-note-label-needed
