Repository nmstate/kubernetes-nmstate, pull requests merged in 2020-03, with the labels that each got.

#443 Use centos8
  build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#444 Add api server probe timeout
  pkg/helper/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#445 Use centos8 nodes
  Makefile
  automation/check-patch.e2e-k8s.sh
  hack/cluster-sync-handler.sh
  hack/flush-secondary-nics.sh
  hack/install-kubevirtci.sh
  hack/install-nm.sh
  test/e2e/get-bridge-vlans-flags-el8.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#446 Stabilize master tests
  test/e2e/bonding_default_interface_test.go
  test/e2e/get-bridge-vlans-flags-el8.sh
  test/e2e/main_test.go
  test/e2e/simple_bridge_and_bond_test.go
  test/e2e/states.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#447 Release v0.16.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#442 use cluster scripts
  .gitignore
  Makefile
  cluster/clean.sh
  cluster/cli.sh
  cluster/down.sh
  cluster/kubeconfig.sh
  cluster/kubectl.sh
  cluster/kubevirtci.sh
  cluster/sync.sh
  cluster/up.sh
  docs/deployment-local-cluster.md
  docs/user-guide-policy-configure-linux-bond-with-vlans.md
  docs/user-guide-policy-configure-linux-bond.md
  hack/cluster-sync-handler.sh
  hack/flush-secondary-nics.sh
  hack/install-kubevirtci.sh
  hack/install-nm.sh
  hack/install-ovs.sh
  test/cmd/kubectl.go
  test/e2e/check-bridge-has-vlans-el8.sh
  test/e2e/get-bridge-vlans-flags-el8.sh
  test/runner/node.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#448 Add consistently check at cluster-sync
  cluster/clean.sh
  cluster/kubevirtci.sh
  cluster/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#449 Upgrade kube-admission-webhook lib
  go.mod
  go.sum
  vendor/github.com/Microsoft/hcsshim/mksyscall_windows.go
  vendor/github.com/globalsign/mgo/bson/bson_corpus_spec_test_generator.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/lib/pq/oid/gen.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/ca.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#428 Removing nodestate_controller and moving its logic to node controller
  deploy/operator.yaml
  docs/user-guide-101-reporting.md
  pkg/controller/add_nodenetworkstate.go
  pkg/controller/node/node_controller.go
  pkg/controller/node/node_controller_test.go
  pkg/controller/nodenetworkstate/nodenetworkstate_controller.go
  pkg/helper/client.go
  test/e2e/main_test.go
  test/e2e/nns_update_timestamp_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#450 Release v0.17.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#430 Use openapi-gen to remove warning
  Makefile
  hack/boilerplate.go.txt
  pkg/apis/nmstate/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/nmstate/v1alpha1/zz_generated.openapi.go
  tools.go
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#454 Run probe after rollback
  pkg/helper/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#460 Release v0.15.4
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#456 Add reboot test for bridge
  test/e2e/default_bridged_network_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#457 [release-0.15] Add reboot test for bridge
  test/e2e/default_bridged_network_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#463 Pin nmstate to 0.1
  build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#438 CNAO integration
  Makefile
  cluster/clean.sh
  cluster/sync.sh
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  hack/render-manifests.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#461 Create CRD for Kubernetes Nmstate Operator
  deploy/crds/nmstate.io_nmstates_crd.yaml
  pkg/apis/nmstate/v1alpha1/nmstate_types.go
  pkg/apis/nmstate/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_nmstate.go
  pkg/controller/nmstate/nmstate_controller.go
  pkg/controller/nmstate/nmstate_controller_test.go
  pkg/controller/nmstate/nmstate_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#467 Add abiltity to specify which image builder to use in Makefile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#471 cleanup examples in documentation
  README.md
  docs/examples/bond-vlan.yaml
  docs/examples/bond.yaml
  docs/examples/dhcp.yaml
  docs/examples/dns.yaml
  docs/examples/ethernet.yaml
  docs/examples/linux-bridge.yaml
  docs/examples/ovs-bridge-iface.yaml
  docs/examples/ovs-bridge.yaml
  docs/examples/route.yaml
  docs/examples/static-ip.yaml
  docs/examples/vlan.yaml
  docs/examples/worker-selector.yaml
  docs/user-guide-102-configuration.md
  docs/user-guide-103-troubleshooting.md
  docs/user-guide-policy-configure-linux-bond-with-vlans.md
  docs/user-guide-policy-configure-linux-bond.md
  docs/user-guide-policy-configure-linux-bridge.md
  docs/user-guide-policy-configure-ovs-bridge.md
  docs/user-guide-policy-configure-vlan-and-dynamic-ip.md
  docs/user-guide/bond0-eth1-eth2_absent.yaml
  docs/user-guide/bond0-eth1-eth2_up.yaml
  docs/user-guide/eth1-eth2_up.yaml
  docs/user-guide/eth666_up.yaml
  docs/user-guide/vlan100_node01_up.yaml
  test/e2e/examples_test.go
  test/e2e/user_guide_test.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#472 Stabilize 0.15 tests
  test/e2e/main_test.go
  test/e2e/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#453 [release-0.15] Annotate tests with polarion IDs
  automation/check-patch.e2e-k8s.sh
  go.mod
  go.sum
  test/e2e/main_test.go
  test/e2e/nnce_conditions_test.go
  test/e2e/node_selector_test.go
  test/e2e/nodes_test.go
  test/e2e/rollback_test.go
  vendor/github.com/chai2010/gettext-go/gettext/hello.go
  vendor/github.com/google/btree/btree_mem.go
  vendor/github.com/lib/pq/oid/gen.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/internal/imports/mkindex.go
  vendor/golang.org/x/tools/internal/imports/mkstdlib.go
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#478 test: Don't use 'sleep 5' at vlan-filtering script
  test/e2e/nnce_conditions_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#480 Add node ready state probe
  pkg/controller/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_controller.go
  pkg/helper/client.go
  pkg/probe/probes.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
