Repository nmstate/kubernetes-nmstate, pull requests merged in 2020-09, with the labels that each got.

#595 Refactor nodeSelector,tolerations,affinity template variables
  deploy/handler/operator.yaml
  pkg/controller/nmstate/nmstate_controller.go
  pkg/render/yaml.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, ok-to-test, release-note-none, size/M

#598 Add bugzilla info to OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#588 build/Dockerfile.operator.openshift: fix COPY path
  build/Dockerfile.operator.openshift
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#597 Add v1alpha1 nncp population test
  test/e2e/handler/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#602 Remove OCP/OKD ci
  automation/check-patch.e2e-ocp.sh
  automation/check-patch.e2e-okd.sh
  automation/check-patch.e2e-operator-ocp.sh
  automation/check-patch.e2e-operator-okd.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#601 Use k8s-1.19 kubevirtci provider
  Makefile
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
  cluster/kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
