Repository nmstate/kubernetes-nmstate, pull requests merged in 2020-07, with the labels that each got.

#571 Kaw 0.9.0
  deploy/handler/role.yaml
  go.mod
  go.sum
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/client.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/cert.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/triple.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/certificate/triple/cert.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#573 Use a env var for polarion '--test-suite-params'
  hack/run-e2e-test-handler.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#576 Kaw 0.11.0
  go.mod
  go.sum
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/cleanup.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#578 Release v0.23.0
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/S

#579 add project logo
  README.md
  logo/black.png
  logo/black.svg
  logo/fullcolor.png
  logo/fullcolor.svg
  logo/white.png
  logo/white.svg
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note, size/XS

#565 Tag release
  Makefile
  cmd/manager/main.go
  hack/bump-version.sh
  hack/prepare-release.sh
  hack/release-notes.tmpl
  hack/release.sh
  hack/render-release-notes.sh
  hack/tag-version.sh
  hack/version.sh
  hack/versions.sh
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, kind/enhancement, kind/infrastructure, lgtm, release-note, size/L

#580 Export the RELEASE_NOTE make var
  Makefile
Labels: approved, dco-signoff: yes, kind/bug, kind/infrastructure, lgtm, release-note, size/XS

#581 Parameterize scc service account reference
  deploy/openshift/scc.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#583 Remove POLARION_TEST_SUITE_PARAMS
  hack/run-e2e-test-handler.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#586 Test active-backup bonding with primary interface
  test/e2e/handler/bonding_default_interface_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#587 Kaw 0.12.0
  cmd/manager/main.go
  deploy/handler/operator.yaml
  go.mod
  go.sum
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
  pkg/webhook/webhook.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/cleanup.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/configuration.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/controller.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/options.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note, size/XL
