Repository nmstate/kubernetes-nmstate, pull requests merged in 2020-12, with the labels that each got.

#623 Reconcile populted NNCP if node is created or modified
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
  test/e2e/handler/node_selector_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#650 tests: Show NNCE if NNCP is not matching
  test/e2e/handler/conditions.go
  test/e2e/handler/main_test.go
  vendor/github.com/onsi/gomega/gstruct/elements.go
  vendor/github.com/onsi/gomega/gstruct/fields.go
  vendor/github.com/onsi/gomega/gstruct/ignore.go
  vendor/github.com/onsi/gomega/gstruct/keys.go
  vendor/github.com/onsi/gomega/gstruct/pointer.go
  vendor/github.com/onsi/gomega/gstruct/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#649 Add Aborted conditionType for policy enactments
  api/shared/nodenetworkconfigurationenactment_types.go
  api/shared/nodenetworkconfigurationpolicy_types.go
  automation/check-patch.e2e-k8s.sh
  controllers/nodenetworkconfigurationpolicy_controller.go
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  pkg/enactmentstatus/conditions/conditions.go
  pkg/enactmentstatus/conditions/counter.go
  pkg/enactmentstatus/conditions/counter_test.go
  pkg/policyconditions/conditions.go
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/nncp_parallel_test.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note, size/L

#643 Bump nmstate to 0.3
  Makefile
  build/Dockerfile
  controllers/nodenetworkconfigurationpolicy_controller.go
  test/e2e/handler/main_test.go
  test/e2e/handler/node_selector_test.go
  test/e2e/handler/states.go
  test/e2e/handler/upgrade_test.go
  test/e2e/handler/user_guide_test.go
  test/e2e/handler/utils.go
  test/reporter/reporter.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#651 Ignore logo files in whitespace.sh script
  hack/whitespace.sh
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#658 Correct the argument for template to release notes
  hack/render-release-notes.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#654 Add NMSTATE_PIN knob to Makefile
  Makefile
  build/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#656 Fix condition checking in helper/client.go UpdateCurrentState
  pkg/helper/client.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#662 update qe-tools to v0.1.7
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/README.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/github.com/onsi/ginkgo/ginkgo/generate_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/main.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/dependencies.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/ginkgo/internal/global/init.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_darwin.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_dragonfly.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_freebsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_linux.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_linux_mips64le.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_netbsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_openbsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_solaris.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_unix.go
  vendor/github.com/onsi/ginkgo/internal/suite/suite.go
  vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XL

#657 Fix bonding e2e test
  test/e2e/handler/bonding_default_interface_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#664 Reduce calls to apiserver at nns updates
  automation/check-patch.e2e-k8s.sh
  controllers/node_controller.go
  controllers/node_controller_test.go
  controllers/nodenetworkstate_controller.go
  main.go
  pkg/helper/client.go
  pkg/nmstatectl/nmstatectl.go
  pkg/node/constants.go
  test/e2e/handler/nns_update_timestamp_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#668 Remove gc-timer at e2e tests when comparing NNS currentState
  controllers/node_controller.go
  pkg/state/filter.go
  test/e2e/handler/nns_update_timestamp_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#669 Delete test-policy at user guide e2e tests
  test/e2e/handler/user_guide_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#655 Add an example policy of removing a bridge with eth port
  docs/examples.md
  docs/examples/detach-bridge-port-and-restore-eth.yaml
  test/e2e/handler/examples_test.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/S
