Repository nmstate/kubernetes-nmstate, pull requests merged in 2020-04, with the labels that each got.

#484 Ensure probes are run after success nmstatectl rollback
  pkg/helper/client.go
  pkg/nmstatectl/nmstatectl.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#483 Run e2e test at workers
  Makefile
  automation/check-patch.e2e-k8s.sh
  cluster/kubevirtci.sh
  test/e2e/conditions.go
  test/e2e/main_test.go
  test/e2e/nnce_conditions_test.go
  test/e2e/prepare.go
  test/e2e/rollback_test.go
  test/e2e/utils.go
  test/runner/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#465 Adapt to external k8s
  Makefile
  automation/check-patch.e2e-k8s.sh
  hack/label-workers.sh
  test/cmd/kubectl.go
  test/e2e/check-bridge-has-vlans-el8.sh
  test/e2e/conditions.go
  test/e2e/demos_test.go
  test/e2e/get-bridge-vlans-flags-el8.sh
  test/e2e/main_test.go
  test/e2e/nnce_conditions_test.go
  test/e2e/openshift.cnv.workflow.sh
  test/e2e/prepare.go
  test/e2e/rollback_test.go
  test/e2e/utils.go
  test/environment/environment.go
  test/runner/node.go
  test/runner/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#488 Introduce a prefix for manifests
  Makefile
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  hack/render-manifests.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, ok-to-test, release-note-none, size/L

#487 Add lock mechanism for handlers instances
  cmd/manager/main.go
  deploy/operator.yaml
  go.mod
  go.sum
  vendor/github.com/nightlyone/lockfile/.gitignore
  vendor/github.com/nightlyone/lockfile/.gitmodules
  vendor/github.com/nightlyone/lockfile/.travis.yml
  vendor/github.com/nightlyone/lockfile/LICENSE
  vendor/github.com/nightlyone/lockfile/README.md
  vendor/github.com/nightlyone/lockfile/appveyor.yml
  vendor/github.com/nightlyone/lockfile/go.mod
  vendor/github.com/nightlyone/lockfile/lockfile.go
  vendor/github.com/nightlyone/lockfile/lockfile_unix.go
  vendor/github.com/nightlyone/lockfile/lockfile_windows.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#490 Add an exclusive lock for nmstate handler instances (#487)
  cmd/manager/main.go
  deploy/operator.yaml
  go.mod
  go.sum
  vendor/github.com/nightlyone/lockfile/.gitignore
  vendor/github.com/nightlyone/lockfile/.gitmodules
  vendor/github.com/nightlyone/lockfile/.travis.yml
  vendor/github.com/nightlyone/lockfile/LICENSE
  vendor/github.com/nightlyone/lockfile/README.md
  vendor/github.com/nightlyone/lockfile/appveyor.yml
  vendor/github.com/nightlyone/lockfile/go.mod
  vendor/github.com/nightlyone/lockfile/lockfile.go
  vendor/github.com/nightlyone/lockfile/lockfile_unix.go
  vendor/github.com/nightlyone/lockfile/lockfile_windows.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#491 Release v0.15.5
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#477 Count only nodes knmstate pods at policy conditions calculation
  deploy/role.yaml
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions.go
  pkg/controller/nodenetworkconfigurationpolicy/policyconditions/conditions_test.go
  test/e2e/webhook_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#489 Cherry pick workflow test
  Makefile
  cluster/ssh.sh
  test/cmd/kubectl.go
  test/e2e/check-bridge-has-vlans-el8.sh
  test/e2e/get-bridge-vlans-flags-el8.sh
  test/e2e/main_test.go
  test/e2e/openshift.cnv.workflow.sh
  test/e2e/utils.go
  test/environment/environment.go
  test/runner/node.go
  test/runner/pod.go
Labels: approved, dco-signoff: yes, kind/test, lgtm, release-note, size/L

#492 Release v0.18.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#493 Add go dep at makefile targets
  Makefile
  version/version.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#495 Stabilize e2e tests after moving to two workers
  cluster/kubevirtci.sh
  test/e2e/check-bridge-has-vlans-el8.sh
  test/e2e/utils.go
  test/e2e/webhook_test.go
Labels: approved, dco-signoff: yes, kind/bug, kind/infrastructure, lgtm, release-note-none, size/M

#501 Add some fixes to clean
  cluster/clean.sh
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#502 Adapt scc.yaml to ocp 4.5
  deploy/openshift/scc.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#503 Release v0.19.0
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#509 Add handler and operator Dockerfiles for openshift
  build/Dockerfile.openshift
  build/Dockerfile.operator.openshift
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note, size/M

#499 add Brad and Yossi to reviewers
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#500 Enable external ocp cluster-sync
  CONTRIBUTING.md
  cluster/sync.sh
Labels: approved, dco-signoff: yes, kind/enhancement, kind/infrastructure, lgtm, release-note, size/M

#513 Move e2e tests to e2e/handler
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/conditions.go
  test/e2e/handler/default_bridged_network_test.go
  test/e2e/handler/examples_test.go
  test/e2e/handler/main_test.go
  test/e2e/handler/multiple_policies_for_same_node_test.go
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/nnce_desiredstate_test.go
  test/e2e/handler/nncp_cleanup_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/node_selector_test.go
  test/e2e/handler/nodes_test.go
  test/e2e/handler/prepare.go
  test/e2e/handler/rollback_test.go
  test/e2e/handler/simple_bridge_and_bond_test.go
  test/e2e/handler/simple_ovs_bridge_test.go
  test/e2e/handler/simple_vlan_and_ip_test.go
  test/e2e/handler/states.go
  test/e2e/handler/user_guide_test.go
  test/e2e/handler/utils.go
  test/e2e/handler/webhook_test.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/M

#518 drop metrics from handler
  cmd/manager/main.go
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/M

#512 Only reconcile a single CR with a specific name
  deploy/crds/nmstate.io_v1alpha1_nmstate_cr.yaml
  pkg/controller/nmstate/nmstate_controller.go
  pkg/controller/nmstate/nmstate_controller_test.go
  pkg/controller/nmstate/nmstate_suite_test.go
  pkg/controller/nmstate/testdata/kubernetes-nmstate/crds/.gitkeep
  pkg/controller/nmstate/testdata/kubernetes-nmstate/handler/.gitkeep
  pkg/controller/nmstate/testdata/kubernetes-nmstate/namespace/.gitkeep
  pkg/controller/nmstate/testdata/kubernetes-nmstate/rbac/.gitkeep
  pkg/names/names.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L
