Repository nmstate/kubernetes-nmstate, pull requests merged in 2020-11, with the labels that each got.

#612 Bump to go 1.15 to get SubjectKeyId at CA certificate
  go.mod
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/flags.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/logger.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#627 Bump OpenShift Dockerfile to golang-1.15 builder
  build/Dockerfile.openshift
  build/Dockerfile.operator.openshift
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#625 [release-0.31] Disable metrics default behaviour
  cmd/manager/main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#624 Disable metrics default behaviour
  main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#632 Resurrect the logos
  logo/black.png
  logo/fullcolor.png
  logo/white.png
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#633 Remove code directories from .dockerignore
  .dockerignore
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#621 page: Move content under docs and create initial site
  .github/workflows/github-pages.yml
  README.md
  automation/check-patch.docs.sh
  automation/publish.sh
  docs/.dockerignore
  docs/.gitignore
  docs/Dockerfile
  docs/Gemfile
  docs/Gemfile.lock
  docs/Makefile
  docs/_config.yaml
  docs/_data/navigation.yaml
  docs/_plugins/include_absolute.rb
  docs/assets/images/logo/fullcolor.png
  docs/deployment.md
  docs/deployment/arbitrary-cluster.md
  docs/deployment/local-cluster.md
  docs/examples.md
  docs/index.md
  docs/user-guide.md
  docs/user-guide/101-reporting.md
  docs/user-guide/102-configuration.md
  docs/user-guide/103-troubleshooting.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#636 Fix NNCE condition Reset function
  pkg/enactmentstatus/conditions/conditions.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#638 Generate operator RBACs using controller-gen
  Makefile
  controllers/nmstate_controller.go
  deploy/operator/role.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#639 Add the operator to publish.sh
  automation/publish.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#640 Fix the publish.sh script
  automation/publish.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#635 knmstate, docs: Remove docker caching
  automation/check-patch.docs.sh
  automation/publish.sh
  docs/Dockerfile
  docs/_config.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#642 Add git name and user at publish.sh
  automation/publish.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#622 Roll out configuration sequentially
  Makefile
  api/shared/nodenetworkconfigurationpolicy_types.go
  automation/check-patch.e2e-k8s.sh
  controllers/nodenetworkconfigurationpolicy_controller.go
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  docs/user-guide/102-configuration.md
  pkg/policyconditions/conditions.go
  test/e2e/handler/conditions.go
  test/e2e/handler/examples_test.go
  test/e2e/handler/multiple_policies_for_same_node_test.go
  test/e2e/handler/nncp_parallel_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/nodes_test.go
  test/e2e/handler/user_guide_test.go
  test/e2e/handler/utils.go
  test/environment/environment.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note, size/L

#645 Reduce default gw probe traces
  pkg/probe/probes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#646 ci, Fix ci commands
  Makefile
  test/e2e/handler/utils.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#647 Activate k8s reporter for handler e2e test
  test/e2e/handler/main_test.go
  test/reporter/reporter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
