Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-01, with the labels that each got.

#676 Bump ruby listen package
  docs/Gemfile.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#680 Document guidelines for using multiple policies
  docs/user-guide/102-configuration.md
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#678 Filter calico interfaces from NNS
  deploy/handler/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#661 Replace "slave" with "port" at e2e tests
  go.mod
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/main_test.go
  test/e2e/handler/simple_bridge_and_bond_test.go
  test/e2e/handler/states.go
  test/e2e/handler/utils.go
  test/runner/pod.go
  test/version/nmstate.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#675 Add a validation webhook for policy changes
  deploy/handler/operator.yaml
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
  pkg/webhook/nodenetworkconfigurationpolicy/handler.go
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation_test.go
  test/e2e/handler/node_selector_test.go
  test/e2e/handler/utils.go
  test/e2e/handler/webhook_test.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/L

#682 Decrease NNS refresh frequency and remove dyn attr
  controllers/labels.go
  controllers/node_controller.go
  controllers/node_controller_test.go
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkstate_controller.go
  go.mod
  go.sum
  pkg/helper/client.go
  pkg/helper/client_test.go
  pkg/node/constants.go
  pkg/state/filter.go
  pkg/state/filter_test.go
  pkg/state/state_suite_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/nodes_test.go
  vendor/github.com/andreyvit/diff/.gitignore
  vendor/github.com/andreyvit/diff/LICENSE
  vendor/github.com/andreyvit/diff/README.md
  vendor/github.com/andreyvit/diff/diff.go
  vendor/github.com/andreyvit/diff/doc.go
  vendor/github.com/andreyvit/diff/trim.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#683 [release-0.37] Decrease NNS refresh frequency and remove dyn attr
  controllers/labels.go
  controllers/node_controller.go
  controllers/node_controller_test.go
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkstate_controller.go
  go.mod
  go.sum
  pkg/helper/client.go
  pkg/helper/client_test.go
  pkg/node/constants.go
  pkg/state/filter.go
  pkg/state/filter_test.go
  pkg/state/state_suite_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/nodes_test.go
  vendor/github.com/andreyvit/diff/.gitignore
  vendor/github.com/andreyvit/diff/LICENSE
  vendor/github.com/andreyvit/diff/README.md
  vendor/github.com/andreyvit/diff/diff.go
  vendor/github.com/andreyvit/diff/doc.go
  vendor/github.com/andreyvit/diff/trim.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#685 Jitter the nns refresh period
  controllers/node_controller.go
  controllers/node_controller_test.go
  pkg/node/constants.go
  pkg/node/refresh.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/M
