Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-09, with the labels that each got.

#816 operator: Fix deletion of newer NMstate CRs
  controllers/nmstate_controller.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note

#798 Delete unused function
  test/e2e/handler/main_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#735 Consolidate error messages
  api/shared/condition_types.go
  controllers/nodenetworkconfigurationpolicy_controller.go
  deploy/crds/nmstate.io_nmstates.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  deploy/crds/nmstate.io_nodenetworkstates.yaml
  pkg/enactmentstatus/conditions/conditions.go
  pkg/enactmentstatus/enactmentstatus_suite_test.go
  pkg/enactmentstatus/message.go
  pkg/enactmentstatus/message_test.go
  test/e2e/handler/error_messages_formatting_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none, ok-to-test

#815 Try updating nncp with non-cached client as backup
  controllers/nodenetworkconfigurationpolicy_controller.go
  pkg/policyconditions/conditions.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#802 Custom infra tolerations and selectors
  api/v1beta1/nmstate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/nmstate_controller.go
  controllers/nmstate_controller_test.go
  deploy/crds/nmstate.io_nmstates.yaml
  deploy/handler/operator.yaml
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note-none, ok-to-test

#824 [Release 0.47] operator: Fix deletion of newer NMstate CRs
  controllers/nmstate_controller.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note

#826 kubevirtci, Simplify kubevirtci.sh script
  cluster/kubevirtci.sh
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#829 Mount ovs socket
  build/Dockerfile.operator.openshift
  controllers/nmstate_controller.go
  controllers/nmstate_controller_test.go
  deploy/handler/operator.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note

#827 kubevirtci, Bump and use k8s-1.21
  Makefile
  cluster/kubevirtci.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#825 PodDisruptionBudget, Update apiVersion
  deploy/handler/operator.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#821 Release 0.47 fix dockerfile openshift
  build/Dockerfile.openshift
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#813 Introduce nodenetworkconfigurationenactment_controller
  api/shared/nodenetworkconfigurationenactment_types.go
  api/v1beta1/nodenetworkconfigurationenactment_types.go
  api/v1beta1/nodenetworkconfigurationenactment_types_test.go
  controllers/nodenetworkconfigurationenactment_controller.go
  controllers/nodenetworkconfigurationenactment_controller_test.go
  main.go
  pkg/enactment/refresh.go
  test/e2e/handler/nncp_cleanup_test.go
  test/e2e/handler/utils.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note-none, ok-to-test

#833 Remove unused travis config
  .travis.yml
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#832 e2e: Remove rollback test that is now obsolete
  test/e2e/handler/rollback_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#838 Return nil when reached maxUnavailable count
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note

#830 infra, arm: Add multiarch build infra
  Makefile
  automation/check-patch.setup.sh
  build/Dockerfile
  build/Dockerfile.operator
  controllers/nmstate_controller.go
  hack/build-manager.sh
  hack/build-push-container.docker.sh
  hack/build-push-container.podman.sh
  hack/init-buildx.sh
  hack/install-go.sh
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note

#840 [release-0.47] Return nil when reached maxUnavailable count
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note
