Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-06, with the labels that each got.

#766 [release-0.37] Add rhrazdil to approvers
  OWNERS
Labels: dco-signoff: yes, release-note-none, size/XS

#764 Pin NMState and NetworkManager to copr version
  build/Dockerfile
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#763 Don't confict with nodeRunningUpdate same node
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/M

#765 Sync unavailableNodeCount at policy Reconcile
  controllers/nodenetworkconfigurationpolicy_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#761 Bump go to 1.16
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#770 Relationship labels, Label self deployed resources
  api/v1alpha1/nodenetworkconfigurationenactment_types.go
  api/v1beta1/nodenetworkconfigurationenactment_types.go
  deploy/handler/operator.yaml
  pkg/helper/client.go
  pkg/names/names.go
  pkg/names/names_suite_test.go
  pkg/names/names_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#771 Avoid incrementing NRU when NNCE is in progress
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
  pkg/enactmentstatus/status.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#774 Revert "[release-0.43] Don't confict with nodeRunningUpdate same node"
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
Labels: dco-signoff: no, do-not-merge/release-note-label-needed, size/M

#775 [release-0.43] Don't confict with nodeRunningUpdate same node (#773)
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/M

#776 [release-0.47] Avoid incrementing NRU when NNCE
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
  pkg/enactmentstatus/status.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#772 Relationship labels, Adapt to new kaw for secrets labeling
  deploy/handler/operator.yaml
  go.mod
  go.sum
  main.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/options.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#777 Control plane, Assign Priority class to pods
  deploy/handler/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#778 Remove go install step
  Makefile
  hack/install-tools.sh
  hack/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#780 [release-0.47] Control plane, Assign Priority class to pods
  deploy/handler/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS
