Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-10, with the labels that each got.

#841 Introduce Byf to functional tests
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/default_bridged_network_test.go
  test/e2e/handler/main_test.go
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/nnce_desiredstate_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/node_selector_test.go
  test/e2e/handler/rollback_test.go
  test/e2e/handler/simple_vlan_and_ip_test.go
  test/e2e/handler/utils.go
  test/e2e/handler/webhook_test.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#844 e2e: wait for re-reconcile after node reboot
  test/e2e/handler/default_bridged_network_test.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#845 Fix MISSING values in handler logs
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/utils.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#848 e2e: check LastTransitionTime instead of polling status
  test/e2e/handler/conditions.go
  test/e2e/handler/default_bridged_network_test.go
Labels: kind/enhancement, dco-signoff: yes, size/S, approved, lgtm, release-note-none
