Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-11, with the labels that each got.

#865 Fix NodeNetworkState e2e tests to use primary NIC name from environment variable
  test/e2e/handler/error_messages_formatting_test.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#868 go, mod: Run make vendor
  go.mod
  go.sum
  vendor/github.com/containerd/containerd/archive/tar_unix.go
  vendor/github.com/containerd/containerd/content/local/store.go
  vendor/github.com/containerd/containerd/metadata/containers.go
  vendor/github.com/containerd/containerd/metadata/content.go
  vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
  vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
  vendor/github.com/containerd/containerd/remotes/docker/pusher.go
  vendor/github.com/containerd/containerd/remotes/docker/resolver.go
  vendor/github.com/containerd/containerd/sys/oom_unix.go
  vendor/github.com/containerd/containerd/sys/oom_windows.go
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/go.mod
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XL, approved, lgtm, release-note-none

#871 infra, release: Skip release notes deps list
  hack/render-release-notes.sh
Labels: dco-signoff: yes, size/XS, release-note-none

#863 Add handler E2E tests for static addresses and routes
  test/e2e/handler/multiple_policies_for_same_node_test.go
  test/e2e/handler/states.go
  test/e2e/handler/static_addr_and_route_test.go
  test/e2e/handler/utils.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#874 Fix bond name creation in e2e tests
  test/e2e/handler/utils.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#873 Fix handler e2e test interface cleanups
  test/e2e/handler/main_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/node_selector_test.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#861 Set ENABLE_OVS var when deploying knmstate with cluster-sync
  build/Dockerfile.operator.openshift
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
  deploy/handler/operator.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#876 Substitute time.Now().Sub with time.Since
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
Labels: kind/enhancement, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#880 Fix typos in User Guide
  docs/user-guide/102-configuration.md
  docs/user-guide/103-troubleshooting.md
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none, ok-to-test

#881 Fix inaccuracy in NMState documentation
  api/v1/nmstate_types.go
  api/v1beta1/nmstate_types.go
  deploy/crds/nmstate.io_nmstates.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#885 Fix defaulting of maxUnavailable when wrong input is provided
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  pkg/node/node_suite_test.go
  pkg/node/nodes.go
  pkg/node/nodes_test.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note

#866 Add handler E2E tests for DNS configuration
  test/e2e/handler/dns_test.go
  test/e2e/handler/main_test.go
  test/e2e/handler/utils.go
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note-none

#886 lint: Integrate golangci-lint
  .github/workflow/check.yaml
  .golangci.yml
  Makefile
  hack/header.tpl
  hack/lint.sh
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#888 actions: Fix github actions directory name
  .github/workflows/check.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#877 Set NNCP Degraded as soon as first enactment fails
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
  test/e2e/handler/nnce_conditions_test.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#890 dependabot: Bump containerd and image-spec
  go.mod
  go.sum
  vendor/github.com/containerd/containerd/images/image.go
  vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
  vendor/github.com/containerd/containerd/remotes/docker/resolver.go
  vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#892 [release-0.52] Fix issue with missing vlans after upgrade
  pkg/helper/bridges.go
  pkg/helper/bridges_test.go
  pkg/helper/client.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note

#891 Fix issue with missing vlans after upgrade
  pkg/helper/bridges.go
  pkg/helper/bridges_test.go
  pkg/helper/client.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note

#893 [Release 0.47] Fix issue with missing vlans after upgrade
  automation/check-patch.e2e-k8s.sh
  pkg/helper/bridges.go
  pkg/helper/bridges_test.go
  pkg/helper/client.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note

#896 automation: Publish ony main branch docs
  automation/publish.sh
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#894 [Release 0.52] Set NNCP Degraded as soon as first enactment fails
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
  test/e2e/handler/nnce_conditions_test.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#879 Add docs on using NMState CR knobs
  docs/user-guide/102-configuration.md
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#898 Update and rework OLM bundle creation
  Makefile
  PROJECT
  bundle.Dockerfile
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  bundle/manifests/nmstate-operator_v1_serviceaccount.yaml
  bundle/manifests/nmstate.io_nmstates.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationenactments.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationpolicies.yaml
  bundle/manifests/nmstate.io_nodenetworkstates.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/.gitkeep
  cluster/sync.sh
  controllers/operator/nmstate_controller.go
  deploy/bases/kubernetes-nmstate-operator.clusterserviceversion.yaml
  deploy/crds/nmstate.io_v1beta1_nodenetworkconfigurationenactment_cr.yaml
  deploy/crds/nmstate.io_v1beta1_nodenetworkstate_cr.yaml
  deploy/examples/nmstate.io_v1_nmstate_cr.yaml
  deploy/examples/nmstate.io_v1_nodenetworkconfigurationpolicy_cr.yaml
  deploy/operator/role.yaml
  hack/render-manifests.go
Labels: kind/enhancement, dco-signoff: yes, size/XXL, approved, lgtm, release-note-none

#900 lint, deadcode: Remove code not used
  .golangci.yml
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  pkg/nmstatectl/nmstatectl.go
  pkg/webhook/nodenetworkconfigurationpolicy/conditions.go
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
  test/e2e/handler/conditions.go
  test/e2e/handler/main_test.go
  test/e2e/handler/states.go
  test/e2e/handler/utils.go
  test/e2e/operator/main_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#901 Fix applying vlan filtering via nmcli
  pkg/helper/bridges.go
  pkg/helper/bridges_test.go
  pkg/helper/client.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note-none

#902 [release-0.52] Fix applying vlan filtering via nmcli
  pkg/helper/bridges.go
  pkg/helper/bridges_test.go
  pkg/helper/client.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note-none

#903 [release-0.47] Fix applying vlan filtering via nmcli
  pkg/helper/bridges.go
  pkg/helper/bridges_test.go
  pkg/helper/client.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note-none

#908 Unconvert linter: remove unnecessary conversions
  .golangci.yml
  pkg/webhook/nodenetworkconfigurationpolicy/conditions.go
  pkg/webhook/nodenetworkconfigurationpolicy/timestamp.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation.go
  test/e2e/handler/utils.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#910 Use Eventually when waiting for policy to be set Degraded
  test/e2e/handler/nnce_conditions_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#907 Whitespace linter: remove unnecessary newlines
  .golangci.yml
  controllers/handler/node_controller.go
  pkg/helper/client.go
  pkg/nmstatectl/nmstatectl.go
  pkg/probe/probes.go
  pkg/webhook/nodenetworkconfigurationpolicy/conditions_test.go
  pkg/webhook/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_suite_test.go
  test/e2e/handler/linuxbridge/gjson.go
  test/e2e/handler/main_test.go
  test/e2e/handler/utils.go
  test/e2e/operator/main_test.go
  test/reporter/reporter.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#909 Staticcheck linter - silence warnings
  .golangci.yml
  controllers/handler/node_controller_test.go
  controllers/handler/nodenetworkconfigurationenactment_controller_test.go
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
  pkg/enactmentstatus/message.go
  pkg/policyconditions/conditions_test.go
  pkg/selectors/labels_test.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#906 Update path to the example nmstate CR in clean.sh
  cluster/clean.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#913 [release-0.52] Use Eventually when waiting for policy to be set Degraded
  test/e2e/handler/nnce_conditions_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#915 [release-0.52] Add timeout when waiting for an enactment to fail
  test/e2e/handler/nnce_conditions_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#912 Remove leader election
  cmd/handler/main.go
Labels: kind/enhancement, dco-signoff: yes, size/S, approved, lgtm, release-note

#914 Add timeout when waiting for an enactment to fail
  test/e2e/handler/nnce_conditions_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#917 Don't wait for node boot when waiting for nncp transition
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/default_bridged_network_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#916 Silence golangci-lint warnings
  .golangci.yml
  api/shared/state_types.go
  api/v1alpha1/nodenetworkstate_types_test.go
  api/v1beta1/nodenetworkstate_types_test.go
  controllers/operator/nmstate_controller.go
  pkg/policyconditions/conditions_test.go
  pkg/state/filter_test.go
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
  test/e2e/handler/examples_test.go
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/node_selector_test.go
  test/reporter/writers.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none
