Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-04, with the labels that each got.

#718 Add execute permission to test_logs directory
  test/reporter/reporter.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#724 Add readiness probe to handler
  deploy/handler/operator.yaml
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note, size/XS

#726 Adapt hack scripts to new release-notes version
  hack/render-release-notes.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#731 Use github.com/gofrs/flock to lock handler
  deploy/handler/operator.yaml
  go.mod
  go.sum
  main.go
  pkg/file/touch.go
  test/e2e/daemonset/daemonset.go
  test/e2e/operator/main_test.go
  test/e2e/operator/nmstate_install_test.go
  vendor/github.com/gofrs/flock/.gitignore
  vendor/github.com/gofrs/flock/.travis.yml
  vendor/github.com/gofrs/flock/LICENSE
  vendor/github.com/gofrs/flock/README.md
  vendor/github.com/gofrs/flock/appveyor.yml
  vendor/github.com/gofrs/flock/flock.go
  vendor/github.com/gofrs/flock/flock_aix.go
  vendor/github.com/gofrs/flock/flock_unix.go
  vendor/github.com/gofrs/flock/flock_winapi.go
  vendor/github.com/gofrs/flock/flock_windows.go
  vendor/github.com/nightlyone/lockfile/.gitmodules
  vendor/github.com/nightlyone/lockfile/.travis.yml
  vendor/github.com/nightlyone/lockfile/LICENSE
  vendor/github.com/nightlyone/lockfile/README.md
  vendor/github.com/nightlyone/lockfile/appveyor.yml
  vendor/github.com/nightlyone/lockfile/go.mod
  vendor/github.com/nightlyone/lockfile/lockfile.go
  vendor/github.com/nightlyone/lockfile/lockfile_unix.go
  vendor/github.com/nightlyone/lockfile/lockfile_windows.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/webhook/server/server.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#733 Fix order of logging calls in handler startup code
  main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, needs-ok-to-test, release-note, size/XS

#736 Bump kube-admission-webhook to 0.15.0
  go.mod
  go.sum
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/manager.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/secret.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/cert.go
  vendor/github.com/qinqon/kube-admission-webhook/pkg/certificate/triple/pem.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#732 Refactor nncp controller
  controllers/nodenetworkconfigurationpolicy_controller.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/L
