Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-12, with the labels that each got.

#919 make: Remove install go infra
  Makefile
  automation/check-patch.setup.sh
  automation/install-go.sh
  hack/render-release-notes.sh
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#921 Fix stylecheck and goconst linters
  .golangci.yml
  controllers/operator/nmstate_controller.go
  pkg/helper/bridges.go
  pkg/node/nodes.go
  pkg/node/nodes_test.go
  pkg/probe/probes.go
  pkg/state/filter.go
  pkg/state/type.go
  test/e2e/deployment/matchers.go
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/conditions.go
  test/e2e/handler/multiple_policies_for_same_node_test.go
  test/e2e/handler/nns_filter_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/simple_vlan_and_ip_test.go
  test/e2e/handler/states.go
  test/e2e/handler/static_addr_and_route_test.go
  test/e2e/handler/utils.go
  test/e2e/operator/main_test.go
  test/runner/node.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#920 Set DNS_TEST_NIC default to primaryNic
  test/e2e/handler/main_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#918 [release-0.52] Fix defaulting of maxUnavailable when wrong input is provided (#885)
  controllers/nodenetworkconfigurationpolicy_controller.go
  pkg/node/node_suite_test.go
  pkg/node/nodes.go
  pkg/node/nodes_test.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note-none

#925 automation: Remove install go
  automation/check-patch.setup.sh
  automation/install-go.sh
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#928 Skip DNS tests blocking tests
  test/e2e/handler/dns_test.go
  test/e2e/handler/static_addr_and_route_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#929 Fix issues in DNS tests
  test/e2e/handler/dns_test.go
  test/e2e/handler/states.go
  test/e2e/handler/static_addr_and_route_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#933 compile: Disable CGO for operator/handler
  hack/build-manager.sh
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note

#897 Intergrate nmpolicy
  api/shared/nodenetworkconfigurationenactment_types.go
  api/shared/nodenetworkconfigurationpolicy_types.go
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  controllers/handler/nodenetworkconfigurationpolicy_controller_test.go
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  go.mod
  go.sum
  pkg/enactmentstatus/conditions/conditions.go
  pkg/nmpolicy/generate.go
  pkg/nmpolicy/generate_test.go
  pkg/nmpolicy/nmpolicy_suite_test.go
  test/e2e/handler/default_bridged_network_test.go
  test/e2e/handler/default_bridged_network_with_nmpolicy_test.go
  test/e2e/handler/error_messages_formatting_test.go
  test/e2e/handler/utils.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationenactment_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/nmpolicy/LICENSE
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/equal.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/types.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/values.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/capture/capture.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/capture/capture_entry.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/expander/state_expander.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/lexer.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/rune.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/scanner/scanner.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/token.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/operations.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/errors.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/parser.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/errors.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/filter.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/path.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/resolver.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/terminal.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/types/types.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/operations.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/types/types.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, approved, lgtm, release-note

#932 hack utility for sorting handler logs
  hack/sort_handler_logs.py
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#936 Provide a way to skip the image builds
  Makefile
  hack/build-push-container.docker.sh
  hack/build-push-container.podman.sh
Labels: kind/enhancement, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#935 webhook: Deny NNCP update if capture is modified
  pkg/webhook/nodenetworkconfigurationpolicy/validation.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation_test.go
  test/e2e/handler/default_bridged_network_with_nmpolicy_test.go
  test/e2e/handler/webhook_test.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#934 Retry when incrementing maxUnavailable
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  pkg/node/nodes.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#938 Upgrade nmpolicy version to nmpolicy-v0.1.0
  go.mod
  go.sum
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/parser.go
  vendor/modules.txt
Labels: kind/enhancement, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#937 Fix nnce formatting
  pkg/enactmentstatus/message.go
  pkg/enactmentstatus/message_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#939 Re-queue request if nnce is not found when populating enactment status
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#940 Change NNCE error message encoding to Gzip
  pkg/enactmentstatus/message.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#941 [release-0.52] Retry when incrementing maxUnavailable
  controllers/nodenetworkconfigurationpolicy_controller.go
  pkg/node/nodes.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#942 deps: Fix NMPolicy bump to v0.1.0
  go.sum
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/types.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/token.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/errors.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/parser.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/errors.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/filter.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/path.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/replace.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/resolver.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note

#945 lint: Increase timeout to 3m
  .github/workflows/check.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#944 e2e: Increse time for checking policy is degraded
  test/e2e/handler/nnce_conditions_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#943 nmpolicy e2e: test moving static ip to a bridge using capture
  test/e2e/handler/states.go
  test/e2e/handler/static_addr_and_route_test.go
  test/e2e/handler/utils.go
Labels: kind/enhancement, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#946 deps: Pin nmpolicy to v0.1.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note

#949 Silence golangci-lint warnings
  .golangci.yml
  pkg/enactmentstatus/conditions/conditions.go
  pkg/helper/node.go
  pkg/nmpolicy/generate_test.go
  test/e2e/handler/multiple_policies_for_same_node_test.go
  test/e2e/operator/main_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#950 Add linux os nodeSelector to handler by default
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
  deploy/handler/operator.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#952 deps: Bump NMPolicy to v0.1.2
  go.mod
  go.sum
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/filter.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note
