Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-02, with the labels that each got.

#690 Skip linux-bridge filtering if no "bridge" section
  pkg/state/filter.go
  pkg/state/filter_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/M

#692 Fix broken URL in comment
  api/shared/state_types.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, needs-ok-to-test, release-note-none, size/XS

#693 Bump k8s to 1.20
  Makefile
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
  cluster/kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#688 Use fmt.Sprintf format a ginkgo Should
  test/e2e/handler/nns_update_timestamp_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#697 Fix the bond example
  docs/examples/bond.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#698 Remove usage of offensive language from user-guide
  docs/user-guide/102-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#700 Set the KUBEVIRT_PROVIDER at the Makefile
  Makefile
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#701 Explicitly unmanage veth interfaces
  build/bin/unmanaged-veth
  deploy/handler/operator.yaml
  main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#705 Revert "Explicitly unmanage veth interfaces (#701)"
  build/bin/unmanaged-veth
  deploy/handler/operator.yaml
  main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
