Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-08, with the labels that each got.

#791 Fix counting of nmstate enabled nodes
  pkg/node/nodes.go
  pkg/policyconditions/conditions_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/S

#792 Add tolerations support for handler daemonset.
  api/v1beta1/nmstate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/nmstate_controller.go
  controllers/nmstate_controller_test.go
  deploy/crds/nmstate.io_nmstates.yaml
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note, ok-to-test

#795 [release-0.43] nmstate node counts
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note

#796 [release-0.37] nmstate node counts
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note

#799 Run handlers on workers only in CI
  cluster/sync.sh
  test/e2e/handler/main_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/node_selector_test.go
  test/e2e/handler/utils.go
Labels: kind/enhancement, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#797 Set max unavailable to 10%
  deploy/handler/operator.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note

#803 e2e tests: Populate nodes list by handler pods
  test/e2e/handler/main_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#804 e2e tests: Return back allNodes variable
  test/e2e/handler/main_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/node_selector_test.go
  test/e2e/handler/utils.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#806 Squash nns controller into node controller
  controllers/node_controller.go
  controllers/node_controller_test.go
  controllers/nodenetworkstate_controller.go
  main.go
  pkg/helper/client.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none, ok-to-test

#810 handler,webhook:use variable to set replicas
  controllers/nmstate_controller.go
  deploy/handler/operator.yaml
Labels: kind/enhancement, dco-signoff: yes, size/XS, approved, lgtm, release-note-none, ok-to-test

#808 Set the node as the owner reference of the enactmant
  api/v1beta1/nodenetworkconfigurationenactment_types.go
  api/v1beta1/nodenetworkconfigurationenactment_types_test.go
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note-none, ok-to-test

#811 vendor, Bump protobuf to v1.3.2
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note-none
