Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-07, with the labels that each got.

#784 Improve release notes
  hack/release-notes.tmpl
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note-none, size/XS

#783 Deploy nmstate on arbitrary clusters through the nmstate operator
  docs/deployment/arbitrary-cluster.md
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#786 Use custom Backoff retries setting for status update
  controllers/nodenetworkconfigurationpolicy_controller.go
  pkg/policyconditions/conditions.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#781 manifests, Update requests sections
  deploy/handler/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#788 [release-0.47] manifests, Update requests sections
  deploy/handler/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
