Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-05, with the labels that each got.

#740 cluster-sync, Extend eventually timeout
  cluster/sync-common.sh
Labels: approved, dco-signoff: yes, kind/bug, lgtm, needs-ok-to-test, release-note-none, size/XS

#741 cluster-sync, Fix Eventually and consistently logic
  cluster/clean.sh
  cluster/sync-common.sh
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/S

#737 Don't create unmatched enactments
  api/shared/nodenetworkconfigurationenactment_types.go
  controllers/nodenetworkconfigurationpolicy_controller.go
  pkg/enactment/enactment.go
  pkg/enactmentstatus/conditions/conditions.go
  pkg/enactmentstatus/conditions/counter.go
  pkg/enactmentstatus/conditions/counter_test.go
  pkg/node/nodes.go
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
  pkg/policyconditions/policyconditions_suite_test.go
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/node_selector_test.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note, size/L

#747 Fix operator e2e test flakiness
  test/e2e/operator/nmstate_install_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#745 Bump nmstate to 1.0
  Makefile
  automation/check-patch.e2e-k8s.sh
  docs/examples/bond-vlan.yaml
  docs/examples/bond.yaml
  docs/user-guide/102-configuration.md
  docs/user-guide/bond0-eth1-eth2_up.yaml
  pkg/helper/bridges_test.go
  test/e2e/handler/main_test.go
  test/version/nmstate.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#750 Improve documentation of maxUnavailable field
  docs/user-guide/102-configuration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#748 Add "Pending" condition to nnce status
  api/shared/nodenetworkconfigurationenactment_types.go
  api/v1alpha1/nodenetworkconfigurationenactment_types.go
  api/v1alpha1/nodenetworkconfigurationpolicy_types.go
  api/v1beta1/nodenetworkconfigurationenactment_types.go
  api/v1beta1/nodenetworkconfigurationpolicy_types.go
  controllers/nodenetworkconfigurationpolicy_controller.go
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  docs/user-guide/102-configuration.md
  docs/user-guide/103-troubleshooting.md
  pkg/enactmentstatus/conditions/conditions.go
  pkg/enactmentstatus/conditions/counter.go
  pkg/enactmentstatus/conditions/counter_test.go
  test/e2e/handler/conditions.go
  test/e2e/handler/nnce_conditions_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#751 Remove master referneces
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  Makefile
  api/shared/nodenetworkstate_util.go
  api/v1beta1/nmstate_types.go
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
  bundle.Dockerfile
  bundle/manifests/nmstate.io_nmstates.yaml
  bundle/metadata/annotations.yaml
  deploy/crds/nmstate.io_nmstates.yaml
  docs/deployment/local-cluster.md
  docs/index.md
  pkg/policyconditions/conditions.go
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#752 Remove nmstate-config ConfigMap
  deploy/handler/operator.yaml
  docs/user-guide/101-reporting.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#754 Validate NodeSelector with the same rules as label
  pkg/webhook/nodenetworkconfigurationpolicy/validation.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#755 Change handler toleration to "operator: exists"
  controllers/nmstate_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#757 Validate NNCP name like a label value
  pkg/webhook/nodenetworkconfigurationpolicy/handler.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation_test.go
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note, size/M

#760 Remove Brad from OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
