Repository nmstate/kubernetes-nmstate, pull requests merged in 2021-03, with the labels that each got.

#709 state, filter: Fix the interpretation of ifaces names
  pkg/state/filter.go
  pkg/state/filter_test.go
  pkg/state/type.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#711 Check nns timestamp depend on currnetState
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/nodes_test.go
  test/e2e/handler/utils.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/L

#710 Bug 1906198: Accept any name for the nmstate resource
  controllers/nmstate_controller.go
  controllers/nmstate_controller_test.go
  test/e2e/operator/nmstate_install_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/M

#715 Change spec.Parallel field with spec.MaxUnavailable
  api/shared/nodenetworkconfigurationpolicy_types.go
  controllers/nodenetworkconfigurationpolicy_controller.go
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  docs/user-guide/102-configuration.md
  docs/user-guide/linux-bridge_maxunavailable.yaml
  go.mod
  pkg/node/nodes.go
  pkg/policyconditions/conditions.go
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/nncp_parallel_test.go
  test/e2e/handler/upgrade_test.go
  test/e2e/handler/utils.go
  test/environment/environment.go
  vendor/github.com/andreyvit/diff/.gitignore
  vendor/github.com/andreyvit/diff/LICENSE
  vendor/github.com/andreyvit/diff/README.md
  vendor/github.com/andreyvit/diff/diff.go
  vendor/github.com/andreyvit/diff/doc.go
  vendor/github.com/andreyvit/diff/trim.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/enhancement, lgtm, release-note, size/XL

#719 Fix maxUnavailable nodes calculation from percentages to only consider matching nodes
  controllers/nodenetworkconfigurationpolicy_controller.go
  pkg/enactment/enactment.go
  pkg/node/nodes.go
  test/e2e/handler/nncp_parallel_test.go
  test/e2e/handler/upgrade_test.go
  test/e2e/handler/utils.go
  test/environment/environment.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#720 Cleanup OWNER files
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#716 Move cert-manager execution to a new pod
  deploy/handler/operator.yaml
  main.go
  pkg/environment/environment.go
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
  pkg/webhook/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#722 Add Radim as a maintainer
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#721 Put back the readiness probe
  deploy/handler/operator.yaml
  pkg/webhook/nodenetworkconfigurationpolicy/server.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
