Repository nmstate/kubernetes-nmstate, pull requests merged in 2022-04, with the labels that each got.

#1034 Bump golangci version to resolve lint failures
  .github/workflows/check.yaml
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1030 Remove mount options from build files
  build/Dockerfile
  build/Dockerfile.operator
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1032 Add vlan-filtering example to the website
  docs/examples.md
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1033 Update Actions Go version to match the project
  .github/workflows/check.yaml
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1035 cluster-up: restart NetworkManager
  cluster/up.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1036 cluster: Use kubectl rollout to deploy
  cluster/sync-common.sh
  cluster/sync-operator.sh
  cluster/sync.sh
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1037 Remove GITHUB_TOKEN from arnested/go-version-action
  .github/workflows/check.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none, ok-to-test

#1040 actions: Remove lint
  .github/workflows/check.yaml
  Makefile
  hack/lint.sh
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1044 [release-0.64] actions: Remove lint
  .github/workflows/check.yaml
  Makefile
  hack/lint.sh
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1042 e2e,operator: re-fetch node when removing label
  test/e2e/operator/nmstate_install_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1043 [release-0.64] e2e,operator: re-fetch node when removing label
  test/e2e/operator/nmstate_install_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1041 Set policy status in reconcile if it's Unknown
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  pkg/policyconditions/conditions.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note

#1038 [release-0.64] Update NNCE LTT only on state change (#1018)
  api/shared/condition_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/condition_types.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note

#1045 build: Use copr nmstate/nmstate-git for future
  Makefile
  build/Dockerfile
  build/install-nmstate.distro.sh
  build/install-nmstate.git.sh
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1048 container: Use stream9 and ubi9-beta
  build/Dockerfile
  build/Dockerfile.operator
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note

#1050 Addressing CVE-2022-21698
  go.mod
  go.sum
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1alpha1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nodenetworkconfigurationenactment_types.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note

#1051 [release-0.64] automation: Copy logs directory to artifacts
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1055 test, handler: Do a lazy read of NNCE on error
  test/e2e/handler/conditions.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1056 Revert "container: Use stream9 and ubi9-beta (#1048)"
  build/Dockerfile
  build/Dockerfile.operator
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note

#1057 examples, vlan: specify mandatory vlan.id and vlan.base-iface
  docs/examples/vlan.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1058 e2e,examples: fix e2e examples
  docs/examples/dns-cleanup.yaml
  docs/examples/dns.yaml
  docs/examples/linux-bridge-vlan.yaml
  test/e2e/handler/examples_test.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1061 nns, controller: consolidate controllers for NNS
  controllers/handler/node_controller.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#1064 Store operator e2e test artifacts in correct directory
  test/e2e/operator/main_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1067 [release 0.47] Fix route interpreted as float
  pkg/state/filter.go
  pkg/state/filter_test.go
  pkg/state/type.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#1065 unit,lint: bump timeout to 10m0s
  hack/lint.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1066 Use kubernetes.io/arch instead of beta.kubernetes.io/arch
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
Labels: kind/enhancement, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1068 controller,nns: remove duplicated controller
  controllers/handler/node_controller.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1069 cluster-sync: Increase rollout timeout
  cluster/sync.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1071 test, reset: Remove reset NNCP if it fail
  test/e2e/handler/utils.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1073 e2e: ignore calico tunl0 interface
  test/e2e/handler/main_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none
