Repository nmstate/kubernetes-nmstate, pull requests merged in 2022-07, with the labels that each got.

#1088 proposal: Host IP pool with NNCP
  design-proposals/discarded/host-ip-pool.md
Labels: dco-signoff: yes, size/L, release-note-none

#1102 Use non cached client for operators node actions
  cmd/operator/main.go
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1104 Correct bundles install modes
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  deploy/bases/kubernetes-nmstate-operator.clusterserviceversion.yaml
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1106 infra, release: Move goflags to main
  hack/release.sh
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1109 kubevirtci: Introduce bump script
  hack/bump-kubevirtci.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1111 Mount ovs socket unconditionally
  build/Dockerfile.operator.openshift
  controllers/nmstate_controller.go
  controllers/nmstate_controller_test.go
  deploy/handler/operator.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1112 Bump kubevirtci
  cluster/kubevirtci.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1113 Grant handler service account permissions to use privileged security context constraint on OCP/OKD
  cluster/clean.sh
  controllers/operator/nmstate_controller.go
  deploy/handler/role.yaml
  deploy/openshift/scc.yaml
  go.mod
  go.sum
  hack/render-manifests.go
  pkg/cluster/cluster.go
  test/e2e/operator/nmstate_install_test.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/doc.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/legacy.go
  vendor/github.com/openshift/api/security/v1/register.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: kind/bug, dco-signoff: yes, size/XXL, approved, lgtm, release-note-none
