Repository nmstate/kubernetes-nmstate, pull requests merged in 2022-06, with the labels that each got.

#1094 Update to operator-sdk 1.21
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: kind/enhancement, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1093 Add labels for pod security standards
  build/Dockerfile.operator
  deploy/handler/namespace.yaml
  deploy/operator/namespace.yaml
  deploy/operator/operator.yaml
Labels: kind/enhancement, dco-signoff: yes, size/S, approved, lgtm, release-note

#1099 go: Disable goproxy
  Makefile
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1096 Make bundle creation more generic
  Makefile
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  bundle/manifests/nmstate.io_nmstates.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationenactments.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationpolicies.yaml
  hack/check-gen.sh
Labels: kind/enhancement, dco-signoff: yes, size/XXL, approved, lgtm, release-note-none

#1092 e2e,handler: use copy-mac-from copy mac from primary iface
  docs/examples/bond.yaml
  test/e2e/handler/bonding_default_interface_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none
