Repository nmstate/kubernetes-nmstate, pull requests merged in 2022-01, with the labels that each got.

#954 docs: Bump ruby gems
  docs/Gemfile.lock
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#953 deps: Bump nmpolicy to v0.2.0
  go.mod
  go.sum
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/capture/capture.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/capture/capture_entry.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/expression/error.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/expression/snippet.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/lexer.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/errors.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/parser.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/resolver.go
  vendor/modules.txt
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note

#948 test nmpolicy for ovs slb aggregation link
  test/e2e/handler/simple_ovs_bridge_and_bond_test.go
  test/e2e/handler/utils.go
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note-none

#958 deps: Pin NetworkManager to 1.34
  cluster/up.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#957 Fix periodic re-reconciles of NNCPs with name equal to node
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note

#959 e2e: don't wait for reboot when testing default bridge IP
  test/e2e/handler/default_bridged_network_with_nmpolicy_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#960 Fix ignoring the error if the probe fails during rollback
  pkg/helper/client.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note, ok-to-test

#961 Use nmcli to obtain NetworkManager version
  controllers/handler/node_controller.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#965 automation: Install go.mod go with gimme
  automation/check-patch.setup.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#951 Wrap long lines to 140 characters
  .golangci.yml
  controllers/handler/node_controller.go
  controllers/handler/node_controller_test.go
  controllers/handler/nodenetworkconfigurationenactment_controller_test.go
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  controllers/operator/nmstate_controller.go
  deploy/operator/role.yaml
  pkg/enactmentstatus/conditions/counter.go
  pkg/enactmentstatus/message_test.go
  pkg/helper/bridges.go
  pkg/helper/client.go
  pkg/nmpolicy/generate.go
  pkg/nmpolicy/generate_test.go
  pkg/nmstatectl/nmstatectl.go
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
  pkg/policyconditions/policyconditions_suite_test.go
  pkg/probe/probes.go
  pkg/state/type.go
  pkg/webhook/nodenetworkconfigurationpolicy/handler.go
  pkg/webhook/nodenetworkconfigurationpolicy/nodenetworkconfigurationpolicy_suite_test.go
  pkg/webhook/nodenetworkconfigurationpolicy/timestamp_test.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation_test.go
  test/e2e/daemonset/matchers.go
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/conditions.go
  test/e2e/handler/default_bridged_network_test.go
  test/e2e/handler/default_bridged_network_with_nmpolicy_test.go
  test/e2e/handler/default_ovs_bridged_network_test.go
  test/e2e/handler/error_messages_formatting_test.go
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/simple_bridge_and_bond_test.go
  test/e2e/handler/simple_ovs_bridge_and_bond_test.go
  test/e2e/handler/static_addr_and_route_test.go
  test/e2e/handler/utils.go
  test/e2e/handler/webhook_test.go
  test/e2e/operator/main_test.go
  test/e2e/operator/nmstate_install_test.go
  test/runner/pod.go
Labels: dco-signoff: yes, size/XL, approved, lgtm, release-note-none

#967 [release-0.52] Fix periodic re-reconciles of NNCPs with name equal to node (#957)
  controllers/nodenetworkconfigurationpolicy_controller.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note

#969 build: Use multistage to build the manager
  Makefile
  build/Dockerfile
  build/Dockerfile.future
  build/Dockerfile.operator
  hack/build-manager.sh
  hack/init-buildx.sh
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#971 operator: Add "resources.requests" for CPU and Mem
  deploy/operator/operator.yaml
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note

#972 operator: Use priority class cluster critical
  deploy/operator/operator.yaml
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note

#955 e2e: Add dhcp unaware DNS tests
  test/e2e/handler/dns_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#975 deps: Bump containerd to v1.5.9
  go.mod
  go.sum
  vendor/github.com/containerd/containerd/version/version.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#974 [release-0.64] backport recent fixes
  cluster/up.sh
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  deploy/operator/operator.yaml
  pkg/helper/client.go
  test/e2e/handler/default_bridged_network_with_nmpolicy_test.go
Labels: dco-signoff: yes, approved, lgtm, release-note-none

#977 deps: Bump nmpolicy to v0.2.1
  go.mod
  go.sum
  pkg/nmpolicy/generate.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/equal.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/types.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/parser.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/errors.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/filter.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/path.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/replace.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/resolver.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/types/json.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/types/types.go
  vendor/modules.txt
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note

#979 cluster: Install only ovs repo
  cluster/up.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none
