Repository nmstate/kubernetes-nmstate, pull requests merged in 2022-02, with the labels that each got.

#983 Fix whitespaces in .github/workflow/release.yml
  .github/workflows/release.yml
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#981 Don't involve notReady nodes in NNCP status calculation
  pkg/node/nodes.go
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note

#968 Fix gocritic linter
  .golangci.yml
  cmd/handler/main.go
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
  pkg/enactmentstatus/conditions/conditions.go
  pkg/enactmentstatus/conditions/counter.go
  pkg/enactmentstatus/status.go
  pkg/helper/client.go
  pkg/node/nodes.go
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
  pkg/probe/probes.go
  pkg/selectors/labels.go
  pkg/selectors/labels_test.go
  pkg/selectors/selectors.go
  pkg/webhook/nodenetworkconfigurationpolicy/conditions.go
  pkg/webhook/nodenetworkconfigurationpolicy/handler.go
  pkg/webhook/nodenetworkconfigurationpolicy/timestamp.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation.go
  pkg/webhook/nodenetworkconfigurationpolicy/validation_test.go
  test/cmd/run.go
  test/e2e/handler/conditions.go
  test/e2e/handler/default_ovs_bridged_network_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/rollback_test.go
  test/e2e/handler/simple_bridge_and_bond_test.go
  test/e2e/handler/simple_ovs_bridge_and_bond_test.go
  test/e2e/handler/states.go
  test/e2e/handler/static_addr_and_route_test.go
  test/e2e/handler/utils.go
  test/environment/environment.go
  test/reporter/reporter.go
  test/reporter/writers.go
  test/runner/pod.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#982 Add progressing condition to NNCP
  api/shared/nodenetworkconfigurationpolicy_types.go
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  pkg/policyconditions/conditions.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationpolicy_types.go
Labels: kind/enhancement, dco-signoff: yes, size/M, approved, lgtm, release-note

#973 e2e: check error msg is well formatted in single spec
  test/e2e/handler/error_messages_formatting_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#985 [release-0.64] Don't involve notReady nodes in status calculation
  pkg/node/nodes.go
  pkg/policyconditions/conditions.go
  pkg/policyconditions/conditions_test.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note

#988 Fix go linter and skip flaky dns tests
  pkg/node/nodes.go
  test/e2e/handler/dns_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#989 infra: use double brackets in cluster/kubevirtci.sh
  cluster/kubevirtci.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#987 Fix issue with Route next-hop-interface being interpreted as float64
  pkg/state/filter.go
  pkg/state/filter_test.go
  pkg/state/type.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note

#992 [release-0.64] Backport dns fixes
  pkg/node/nodes.go
  test/e2e/handler/dns_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#991 [release-0.64] Fix issue with Route next-hop-interface being interpreted as float64
  pkg/state/filter.go
  pkg/state/filter_test.go
  pkg/state/type.go
Labels: kind/bug, dco-signoff: yes, size/L, approved, lgtm, release-note

#993 [release 0.52] Fix numeric iface name in route
  Makefile
  build/Dockerfile
  controllers/node_controller.go
  controllers/node_controller_test.go
  deploy/handler/operator.yaml
  docs/user-guide/101-reporting.md
  pkg/state/filter.go
  pkg/state/filter_test.go
  pkg/state/type.go
  test/e2e/handler/nns_filter_test.go
Labels: dco-signoff: yes, size/XL, approved, lgtm, release-note

#994 [release0.52] Install docs on main only
  automation/publish.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#997 cluster: Unpin NetworkManager 1.34
  cluster/up.sh
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note
