Repository nmstate/kubernetes-nmstate, pull requests merged in 2022-05, with the labels that each got.

#1052 rbac: Add missing cluster-reader verbs
  build/Dockerfile.operator
  build/Dockerfile.operator.openshift
  controllers/operator/nmstate_controller.go
  deploy/handler/cluster_role.yaml
  test/e2e/operator/nmstate_install_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#1060 e2e, examples: Add test for an DNS cleanup example
  docs/examples/dns-cleanup.yaml
  test/e2e/handler/examples_test.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1075 test: Wait for terminal NNCP status
  test/e2e/handler/conditions.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1076 api: Fix linters
  api/hack/header.tpl
  api/names/names.go
  api/names/names_suite_test.go
  api/names/names_test.go
  api/shared/condition_types.go
  api/shared/condition_types_test.go
  api/shared/nodenetworkconfigurationenactment_types.go
  api/shared/nodenetworkconfigurationpolicy_types.go
  api/shared/shared_suite_test.go
  api/shared/state_types.go
  api/v1/nmstate_types.go
  api/v1alpha1/nodenetworkconfigurationenactment_types.go
  api/v1alpha1/nodenetworkconfigurationpolicy_types.go
  api/v1alpha1/nodenetworkstate_types_test.go
  api/v1alpha1/v1alpha1_suite_test.go
  api/v1beta1/nodenetworkconfigurationenactment_types.go
  api/v1beta1/nodenetworkconfigurationenactment_types_test.go
  api/v1beta1/nodenetworkstate_types_test.go
  api/v1beta1/v1beta1_suite_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#986 e2e: kubernetes nmstate operator upgrade tests
  Makefile
  automation/check-patch.e2e-upgrade-k8s.sh
  go.mod
  go.sum
  hack/previous-minor-version.sh
  hack/run-e2e-test-upgrade.sh
  test/doc/examples.go
  test/e2e/handler/bonding_default_interface_test.go
  test/e2e/handler/default_bridged_network_test.go
  test/e2e/handler/default_bridged_network_with_nmpolicy_test.go
  test/e2e/handler/default_ovs_bridged_network_test.go
  test/e2e/handler/error_messages_formatting_test.go
  test/e2e/handler/examples_test.go
  test/e2e/handler/multiple_policies_for_same_node_test.go
  test/e2e/handler/nnce_conditions_test.go
  test/e2e/handler/nnce_desiredstate_test.go
  test/e2e/handler/nncp_cleanup_test.go
  test/e2e/handler/nncp_parallel_test.go
  test/e2e/handler/nns_update_timestamp_test.go
  test/e2e/handler/node_selector_test.go
  test/e2e/handler/rollback_test.go
  test/e2e/handler/upgrade_test.go
  test/e2e/handler/user_guide_test.go
  test/e2e/handler/utils.go
  test/e2e/handler/webhook_test.go
  test/e2e/operator/main_test.go
  test/e2e/operator/nmstate_install_test.go
  test/e2e/operator/operator.go
  test/e2e/policy/conditions.go
  test/e2e/upgrade/.gitignore
  test/e2e/upgrade/main_test.go
  test/e2e/upgrade/upgrade_test.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, approved, lgtm, release-note-none

#1078 Fix typo in condition's heartbeat attribute
  api/shared/condition_types.go
  api/shared/condition_types_test.go
  bundle/manifests/nmstate.io_nmstates.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationenactments.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationpolicies.yaml
  bundle/manifests/nmstate.io_nodenetworkstates.yaml
  deploy/crds/nmstate.io_nmstates.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  deploy/crds/nmstate.io_nodenetworkstates.yaml
  docs/user-guide/102-configuration.md
  docs/user-guide/103-troubleshooting.md
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/condition_types.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#1079 Let Ginkgo recover on fail in runAndWait()
  test/reporter/reporter.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1020 linux-bridge: Add test to propertly check vlan
  test/e2e/handler/simple_bridge_and_bond_test.go
  test/e2e/handler/states.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1080 e2e: Fix upgrade lane
  dns-cleanup.yaml
  docs/examples/route.yaml
  docs/examples/static-ip.yaml
  examples.tsr.gz
  file.tar.gz
  linux-10-20-novlan.yaml
  linux-10-20.yaml
  ovs-bridge.yaml
  test/doc/examples.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#1082 Remove files added by accident
  dns-cleanup.yaml
  examples.tsr.gz
  file.tar.gz
  linux-10-20-novlan.yaml
  linux-10-20.yaml
  ovs-bridge.yaml
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#1085 OCI: Support podman
  Makefile
  automation/check-patch.docs.sh
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
  automation/check-patch.e2e-upgrade-k8s.sh
  automation/check-patch.unit-test.sh
  automation/publish.sh
  cluster/kubevirtci.sh
  hack/build-push-container.docker.sh
  hack/build-push-container.podman.sh
  hack/detect_cri.sh
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1089 podman: Use full image name
  automation/check-patch.docs.sh
  automation/publish.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none
