Repository nmstate/kubernetes-nmstate, pull requests merged in 2022-10, with the labels that each got.

#1125 Enable caching in builds again
  build/Dockerfile
  build/Dockerfile.operator
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1129 [release-0.64] Bump kubevirtci
  Makefile
  cluster/kubevirtci.sh
  cluster/up.sh
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1128 [release-0.64] probes: retry to get name server list with 2m timeout
  pkg/probe/probes.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note
