Repository nmstate/kubernetes-nmstate, pull requests merged in 2022-09, with the labels that each got.

#1118 Respect CR node selector for NMState handler
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note, ok-to-test

#1119 Add test exercising lldp configuration with nmpolicy
  docs/examples/lldp.yaml
  go.mod
  go.sum
  test/e2e/handler/lldp_with_nmpolicy_test.go
  test/e2e/handler/utils.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/types.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/lexer.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/rune.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/token.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/parser.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/replace.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/resolver.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note

#1120 e2e,upgrade: fall back to current examples if needed
  test/e2e/upgrade/upgrade_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1116 Refact probe timeouts
  pkg/probe/probes.go
  test/e2e/handler/error_messages_formatting_test.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#1121 probes: remove leftover Println
  pkg/probe/probes.go
Labels: dco-signoff: yes, size/XS, release-note-none

#1122 e2e,doc: Add LLDP example
  docs/examples/lldp.yaml
  test/doc/examples.go
  test/e2e/upgrade/upgrade_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note

#1123 handler: Install plugin-ovsdb
  build/Dockerfile.openshift
  build/install-nmstate.distro.sh
  build/install-nmstate.git.sh
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note
