Repository nmstate/kubernetes-nmstate, pull requests merged in 2022-03, with the labels that each got.

#1000 [release-0.64] capture: Get currentState from cli
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  controllers/handler/nodenetworkconfigurationpolicy_controller_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note

#996 e2e: Run skipped OVS tests
  test/e2e/handler/default_ovs_bridged_network_test.go
  test/e2e/handler/nncp_cleanup_test.go
  test/e2e/handler/utils.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1003 Add Affinity to NMstate CR
  api/v1/nmstate_types.go
  api/v1/zz_generated.deepcopy.go
  controllers/operator/nmstate_controller.go
  deploy/crds/nmstate.io_nmstates.yaml
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nmstate_types.go
Labels: dco-signoff: yes, size/XXL, approved, lgtm, release-note

#1006 Ensure NNCP controllers Reconcile is not run in parallel
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1008 [release-0.64] bump nmpolicy 0.2.1
  go.mod
  go.sum
  pkg/nmpolicy/generate.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/zz_generated.deepcopy.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/equal.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/types.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/parser.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/errors.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/filter.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/path.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/replace.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/resolver.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/types/json.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/types/types.go
  vendor/modules.txt
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note

#1009 build: Use go cross compiling instead of qemu
  Makefile
  build/Dockerfile
  build/Dockerfile.future
  build/Dockerfile.operator
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1010 Explain what MaxUnavailableLimitReached means
  pkg/enactmentstatus/conditions/conditions.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note

#995 Fix golangci linters
  .golangci.yml
  cmd/handler/main.go
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  pkg/policyconditions/conditions.go
Labels: dco-signoff: yes, size/L, approved, lgtm

#1013 [release-0.52] Timeout if Pending takes too long (#854)
  api/shared/nodenetworkconfigurationpolicy_types.go
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  pkg/helper/client.go
  pkg/probe/probes.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note

#1012 webhook: Distribute webhook at control-plane nodes
  deploy/handler/operator.yaml
  test/e2e/operator/main_test.go
  test/e2e/operator/nmstate_install_test.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#1017 dependabot: containerd 1.5.10, docker distro 2.8.1
  go.mod
  go.sum
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1014 cluster: Bump k8s and kubevirtci
  Makefile
  cluster/kubevirtci.sh
  cluster/up.sh
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1021 e2e: retry when labelling nodes
  test/e2e/operator/nmstate_install_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1023 display Reason column when listing NNCPs
  api/v1/nodenetworkconfigurationpolicy_types.go
  api/v1alpha1/nodenetworkconfigurationpolicy_types.go
  api/v1beta1/nodenetworkconfigurationenactment_types.go
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note

#1027 [release-0.47] Timeout if Pending takes too long
  api/shared/nodenetworkconfigurationpolicy_types.go
  build/Dockerfile
  controllers/nodenetworkconfigurationpolicy_controller.go
  controllers/nodenetworkconfigurationpolicy_controller_test.go
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  pkg/helper/client.go
  pkg/probe/probes.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note

#1026 Adapt automation to new logs dir
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1028 Nmstate add selfsigned api
  api/v1/nmstate_types.go
  api/v1/zz_generated.deepcopy.go
  controllers/operator/nmstate_controller.go
  deploy/crds/nmstate.io_nmstates.yaml
  deploy/handler/operator.yaml
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/zz_generated.deepcopy.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1alpha1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nodenetworkconfigurationenactment_types.go
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note
