Repository nmstate/kubernetes-nmstate, pull requests merged in 2023-04, with the labels that each got.

#1169 build: Install nmstate from c9s
  build/install-nmstate.distro.sh
Labels: dco-signoff: yes, size/XS, release-note-none

#1165 Don't deploy UI Plugin resources if the manifests are missing
  controllers/operator/nmstate_controller.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note, ok-to-test

#1175 cluster: Skip NM auto-profile for sec interfaces
  cluster/up.sh
  pkg/probe/probes.go
  test/e2e/handler/rollback_test.go
  test/e2e/policy/conditions.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1177 e2e, handler: Don't put interfaces down
  cluster/up.sh
  test/e2e/handler/dns_test.go
  test/e2e/handler/multiple_policies_for_same_node_test.go
  test/e2e/handler/simple_ovs_bridge_and_bond_test.go
  test/e2e/handler/states.go
  test/e2e/handler/utils.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note

#1171 handler: Remove nmcli vlan-filtering activation
  build/Dockerfile
  controllers/handler/node_controller.go
  pkg/bridge/bridge.go
  pkg/bridge/bridge_test.go
  pkg/client/client.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkstate_types.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note

#1170 handler: Remove link unavailable w/a
  pkg/nmstatectl/nmstatectl.go
  pkg/nmstatectl/unavailable_link_workaround.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note

#1179 openshift, handler: remove plugin-ovsdb dep
  build/Dockerfile.openshift
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note

#1180 Enable ipv4 and ipv6 on primary nic when resetting
  test/e2e/handler/states.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1181 handler: Propertly filter unmanaged veth
  pkg/state/filter.go
  pkg/state/filter_test.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#1183 build: Use ubi9 go-toolset to compile golang
  Makefile
  build/Dockerfile
  build/Dockerfile.operator
Labels: dco-signoff: yes, size/M, release-note
