Repository nmstate/kubernetes-nmstate, pull requests merged in 2023-01, with the labels that each got.

#1132 go: Bump to v1.18
  .golangci.yml
  api/go.sum
  cmd/handler/main.go
  cmd/operator/main.go
  controllers/operator/nmstate_controller.go
  go.mod
  go.sum
  hack/lint.sh
  pkg/probe/probes.go
  pkg/webhook/nodenetworkconfigurationpolicy/timestamp.go
Labels: dco-signoff: yes, size/XL, approved, lgtm, release-note

#1135 docs: Pin ruby to 3.1
  automation/check-patch.docs.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1134 docker: Remove buildx init/install
  hack/build-push-container.docker.sh
  hack/init-buildx.sh
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1138 handler: Temporaly use Gris repo
  build/Dockerfile
  build/install-nmstate.user.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1137 handler: Rollback always before Apply
  pkg/client/client.go
  test/cmd/run.go
  test/e2e/handler/pending_checkpoint_test.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#1140 Update goutils dependency to v1.1.1
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1143 [release-0.64] handler: Temporaly use Gris repo
  build/Dockerfile
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1141 [release-0.64] Update goutils dependency to v1.1.1
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1144 Revert "docker: Remove buildx init/install (#1134)"
  hack/build-push-container.docker.sh
  hack/init-buildx.sh
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1145 [Release 0.64] OCI: Support podman
  Makefile
  automation/check-patch.docs.sh
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-operator-k8s.sh
  automation/check-patch.unit-test.sh
  automation/publish.sh
  cluster/kubevirtci.sh
  hack/build-push-container.docker.sh
  hack/build-push-container.podman.sh
  hack/detect_cri.sh
Labels: kind/enhancement, dco-signoff: yes, size/M, approved, lgtm, release-note-none
