Repository nmstate/kubernetes-nmstate, pull requests merged in 2024-04, with the labels that each got.

#1232 lint: Use binary golangci-lint
  hack/lint.sh
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1221 handler: Expose nmstatectl stats as k8s metrics
  .golangci.yml
  Makefile
  api/shared/nodenetworkconfigurationenactment_types.go
  automation/check-patch.e2e-operator-k8s.sh
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationenactments.yaml
  cluster/kubevirtci.sh
  cmd/handler/main.go
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
  controllers/metrics/nodenetworkconfigurationenactment_controller.go
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments.yaml
  deploy/handler/cluster_role.yaml
  deploy/handler/namespace.yaml
  deploy/handler/operator.yaml
  deploy/handler/role.yaml
  deploy/handler/role_binding.yaml
  deploy/operator/role.yaml
  go.mod
  hack/prom_metric_linter.sh
  pkg/environment/environment.go
  pkg/monitoring/metrics.go
  pkg/nmstatectl/nmstatectl.go
  test/e2e/handler/metrics.go
  test/e2e/handler/metrics_test.go
  test/e2e/operator/main_test.go
  test/e2e/operator/nmstate_install_test.go
  test/e2e/operator/operator.go
  test/e2e/upgrade/main_test.go
  test/reporter/writers.go
  test/runner/pod.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationenactment_types.go
Labels: kind/enhancement, dco-signoff: yes, size/XL, approved, lgtm, release-note

#1233 metrics: change port used by metrics server
  cmd/handler/main.go
  deploy/handler/operator.yaml
  test/e2e/handler/metrics.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1236 e2e, handler: Check neighbors at lldp test
  test/e2e/handler/lldp_with_nmpolicy_test.go
  test/e2e/handler/utils.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note
