Repository nmstate/kubernetes-nmstate, pull requests merged in 2024-06, with the labels that each got.

#1244 operator: Add placeholder for kube-rbac-proxy
  Makefile
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
  deploy/handler/operator.yaml
  deploy/operator/operator.yaml
  hack/render-manifests.go
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note

#1245 operator: configurable placeholder for kube-rbac-proxy
  Makefile
Labels: kind/enhancement, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1246 deps: Bump go to 1.22.4
  Makefile
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  build/Dockerfile
  build/Dockerfile.operator
  build/install-go.sh
  bundle/manifests/nmstate.io_nmstates.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationenactments.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationpolicies.yaml
  bundle/manifests/nmstate.io_nodenetworkstates.yaml
  deploy/crds/nmstate.io_nmstates.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  deploy/crds/nmstate.io_nodenetworkstates.yaml
  deploy/operator/role.yaml
  go.mod
Labels: dco-signoff: yes, size/XXL, release-note-none

#1247 deps: Pin go to 1.22
  automation/check-patch.setup.sh
  build/install-go.sh
  go.mod
Labels: dco-signoff: yes, size/S, lgtm, release-note

#1248 e2e: don't require empty starting state for bridge mappings
  test/e2e/handler/nns_ovn.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none
