Repository nmstate/kubernetes-nmstate, pull requests merged in 2024-07, with the labels that each got.

#1254 hack: use full name for qemu container image
  hack/qemu-user-static.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1253 test: add DNS tests without interface configuration
  test/e2e/handler/dns_test.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1251 OCPBUGS-36487: Update consoleplugin version
  deploy/openshift/ui-plugin/consoleplugin.yaml
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none
