Repository nmstate/kubernetes-nmstate, pull requests merged in 2024-09, with the labels that each got.

#1263 Openshift replace cert manager with openshift cert service
  controllers/operator/nmstate_controller.go
  deploy/handler/operator.yaml
  test/e2e/operator/operator.go
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note

#1265 openshift: Use handler namespace for cleanup
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note

#1267 Use `nmstatectl apply` instead of `nmstatectl set`
  pkg/nmstatectl/nmstatectl.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none, Wait_Review
