Repository nmstate/kubernetes-nmstate, pull requests merged in 2025-09, with the labels that each got.

#1363 logs: when deleting non-existing enactment, write a message
  controllers/handler/nodenetworkconfigurationpolicy_controller.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1369 handler: reduce cyclomatic complexity
  Makefile
  cmd/handler/main.go
  hack/prom_metric_linter.sh
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#1366 Introduce the Security file
  SECURITY.md
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1368 handler: allow configuring the metrics bind port
  api/v1/nmstate_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1beta1/nmstate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/nmstate.io_nmstates.yaml
  cmd/handler/main.go
  controllers/operator/nmstate_controller.go
  deploy/crds/nmstate.io_nmstates.yaml
  deploy/handler/operator.yaml
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/zz_generated.deepcopy.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/zz_generated.deepcopy.go
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note

#1373 ci: Add .gemini/config.yaml
  .gemini/config.yml
Labels: dco-signoff: yes, size/S, release-note-none

#1374 Fix nmstate-console-plugin NetworkPolicy
  deploy/openshift/ui-plugin/network_policy.yaml
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note
