Repository nmstate/kubernetes-nmstate, pull requests merged in 2025-03, with the labels that each got.

#1297 OPNET-614: Configurable DNS probe
  api/v1/nmstate_types.go
  api/v1/zz_generated.deepcopy.go
  automation/check-patch.e2e-k8s.sh
  bundle/manifests/nmstate.io_nmstates.yaml
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
  deploy/crds/nmstate.io_nmstates.yaml
  deploy/handler/operator.yaml
  pkg/probe/probes.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/zz_generated.deepcopy.go
Labels: dco-signoff: yes, size/L, approved, lgtm, release-note-none

#1302 operator: Continue on cleanup NotFound errors
  controllers/operator/nmstate_controller.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note

#1304 api: remove v1alpha1
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/nodenetworkconfigurationenactment_types.go
  api/v1alpha1/nodenetworkconfigurationpolicy_types.go
  api/v1alpha1/nodenetworkstate_types.go
  api/v1alpha1/nodenetworkstate_types_test.go
  api/v1alpha1/v1alpha1_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationenactments.yaml
  bundle/manifests/nmstate.io_nodenetworkconfigurationpolicies.yaml
  bundle/manifests/nmstate.io_nodenetworkstates.yaml
  cmd/handler/main.go
  cmd/operator/main.go
  deploy/crds/nmstate.io_nodenetworkconfigurationenactments.yaml
  deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml
  deploy/crds/nmstate.io_nodenetworkstates.yaml
  test/e2e/handler/upgrade_test.go
  test/env/env.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1alpha1/groupversion_info.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1alpha1/nodenetworkconfigurationenactment_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1alpha1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1alpha1/nodenetworkstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: kind/enhancement, dco-signoff: yes, size/XXL, approved, lgtm, release-note

#1309 test: extend logs collected after upgrade CI job
  automation/check-patch.e2e-upgrade-k8s.sh
Labels: kind/enhancement, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1313 OPNET-650: Add lifecycle optimizations
  Makefile
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  deploy/handler/operator.yaml
  deploy/openshift/ui-plugin/deployment.yaml
  hack/render-manifests.go
Labels: kind/enhancement, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1314 deps: bump golangci-lint to 1.64.7
  hack/lint.sh
Labels: kind/enhancement, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1311 OPNET-647: Implement CPU and memory limits
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  deploy/handler/operator.yaml
  deploy/openshift/ui-plugin/deployment.yaml
  deploy/operator/operator.yaml
Labels: kind/enhancement, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1315 OPNET-648: Add readiness and healthiness probes
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-upgrade-k8s.sh
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  cluster/sync-operator.sh
  cmd/operator/main.go
  deploy/handler/operator.yaml
  deploy/openshift/ui-plugin/deployment.yaml
  deploy/operator/operator.yaml
Labels: kind/enhancement, dco-signoff: yes, size/L, approved, lgtm, release-note-none
