Repository nmstate/kubernetes-nmstate, pull requests merged in 2025-01, with the labels that each got.

#1279 e2e, handler: Simplify vlan_filtering 0 check
  test/e2e/handler/simple_bridge_and_bond_test.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1278 kubevirtci: Bump latest to k8s-1.32
  Makefile
  cluster/kubevirtci.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1280 OCPBUGS-44596: Mount OVS directory instead of socket file
  deploy/handler/operator.yaml
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#1283 Allow configuring node placement for nmstate-console-plugin
  api/v1/nmstate_types.go
  bundle/manifests/nmstate.io_nmstates.yaml
  controllers/operator/nmstate_controller.go
  deploy/crds/nmstate.io_nmstates.yaml
  deploy/openshift/ui-plugin/deployment.yaml
Labels: kind/bug, dco-signoff: yes, size/M, approved, lgtm, release-note, ok-to-test

#1287 fix(CONTRIBUTING): link to local virtualized cluster guide
  CONTRIBUTING.md
Labels: dco-signoff: yes, size/XS, do-not-merge/release-note-label-needed

#1277 nmpolicy: Use nmstatectl policy instead of go lib
  api/go.sum
  docs/examples/lldp.yaml
  go.mod
  go.sum
  pkg/nmpolicy/generate.go
  pkg/nmpolicy/generate_test.go
  pkg/nmstatectl/nmstatectl.go
  test/e2e/handler/nnce_conditions_test.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/zz_generated.deepcopy.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/nmstate/nmpolicy/LICENSE
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/equal.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/types.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/ast/values.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/capture/capture.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/capture/capture_entry.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/expander/state_expander.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/expression/error.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/expression/snippet.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/lexer.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/rune.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/scanner/scanner.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/lexer/token.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/operations.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/errors.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/parser/parser.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/errors.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/filter.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/path.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/replace.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/resolver.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/visitor.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/resolver/walk.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/internal/types/types.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/operations.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/types/json.go
  vendor/github.com/nmstate/nmpolicy/nmpolicy/types/types.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, approved, lgtm, release-note
