Repository nmstate/kubernetes-nmstate, pull requests merged in 2025-07, with the labels that each got.

#1349 netpol: use targeted policy for deny-all
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
  deploy/handler/network_policy.yaml
  deploy/operator/operator.yaml
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1350 Make lint.sh download and execution compatible with Darwin/arm64
  hack/lint.sh
Labels: kind/enhancement, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1352 perf: increase memory limits
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  deploy/handler/operator.yaml
  deploy/openshift/ui-plugin/deployment.yaml
  deploy/operator/operator.yaml
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note
