Repository nmstate/kubernetes-nmstate, pull requests merged in 2025-02, with the labels that each got.

#1295 go: Pin to 1.22.12
  automation/check-patch.setup.sh
  build/install-go.sh
  go.mod
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, release-note

#1294 Enable debug logging of nmstate apply
  pkg/nmstatectl/nmstatectl.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note, Wait_Review

#1298 e2e, handler: Distill initial suite state
  test/e2e/handler/main_test.go
  test/e2e/handler/utils.go
Labels: dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1281 design-proposal: dns probe name customize
  design-proposals/customize-dns-probe-globally.md
Labels: dco-signoff: yes, size/M, release-note-none
