Repository nmstate/kubernetes-nmstate, pull requests merged in 2025-05, with the labels that each got.

#1333 cluster: Use sha digest for manifests
  cluster/sync-common.sh
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note-none

#1323 openshift, operator: Add workload annotation
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  deploy/handler/operator.yaml
  deploy/operator/operator.yaml
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note

#1335 NO-ISSUE: Add build script for Darwin (macOS)
  CONTRIBUTING.md
  Makefile
  bundle.Dockerfile
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  hack/build-push-container.docker.linux.sh
  hack/build-push-container.podman.darwin.sh
  hack/build-push-container.podman.linux.sh
  hack/check-gen.sh
  hack/opm.sh
Labels: kind/enhancement, dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1342 automation: Dump pods at individual files
  automation/check-patch.e2e-k8s.sh
  automation/check-patch.e2e-upgrade-k8s.sh
Labels: dco-signoff: yes, size/M, approved, lgtm, release-note-none

#1341 probes: Add nmstatectl show verbose output
  cmd/handler/main.go
  deploy/handler/operator.yaml
  pkg/log/writer.go
  pkg/nmstatectl/nmstatectl.go
Labels: kind/enhancement, dco-signoff: yes, size/M, approved, lgtm, release-note

#1338 operator: fix handicapped error messages
  controllers/operator/nmstate_controller.go
Labels: kind/bug, dco-signoff: yes, size/S, approved, lgtm, release-note-none
